'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const page=await b.newPage({serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/princess/?heads=natural&v=49');let total=0;
 for(const princessId of 'snow cinder rapunzel mermaid thumb kongjwi briar moon frost sahara lotus sunny'.split(' ')){
  const result=await page.evaluate(async princessId=>{const p=PRINCESSES.find(p=>p.id===princessId),fail=[],c=document.createElement('canvas');c.width=420;c.height=680;const ctx=c.getContext('2d',{willReadFrequently:true});let count=0;
   for(const d of DRESSES)for(const shoe of SHOES){const st={...defaultState(p),dress:{id:d.id,color:'#439cdd'},shoes:{id:shoe.id,color:'#439cdd'},crown:null,neck:null,hand:null,back:null,pet:null},before=JSON.stringify(st),svg=await buildExportSvg(st,p),doc=new DOMParser().parseFromString(svg,'image/svg+xml');doc.querySelector('[data-studio-background]')?.remove();const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(doc)],{type:'image/svg+xml'})),im=new Image();im.src=url;await Promise.race([im.decode(),new Promise((_,reject)=>setTimeout(()=>reject(Error('decode timeout '+d.id+'/'+shoe.id)),15000))]);ctx.clearRect(0,0,420,680);ctx.drawImage(im,0,0);URL.revokeObjectURL(url);const px=ctx.getImageData(0,0,420,680).data;let ink=0;for(let k=3;k<px.length;k+=4)if(px[k]>230)ink++;if(ink<15000)fail.push(`${d.id}/${shoe.id}: missing art ${ink}`);
    if(JSON.stringify(st)!==before)fail.push('state changed');
    if(d.id!=='tail'){const g=PrincessWardrobe.geometry(d.id,p,PrincessStudio.identities,PrincessStudio.headAnchors),fit=PrincessFootwear.layout(d.id,shoe.id);for(const side of [0,1])for(const y of [fit.top+5,fit.cutY+3,fit.sole-16]){const [x]=PrincessFootwear.legAt(d.id,side,y),xx=Math.round(g.x+x*g.scale),yy=Math.round(24+.96*(24+g.y+y*g.scale)),alpha=px[(yy*420+xx)*4+3];if(alpha<230)fail.push(`${d.id}/${shoe.id}: transparent leg ${side}/${y} alpha=${alpha}`);}}
    count++;
   }return {count,fail};},princessId);assert.deepEqual(result.fail,[],princessId);total+=result.count;console.log('PASS raster',princessId,result.count);
 }assert.equal(total,1404);assert.deepEqual(errors,[]);console.log('PASS all 1404 rendered combinations, no transparent leg gaps or missing art');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
