const{chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
(async()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'slime-friend-')),b=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{const c=await b.newContext({viewport:{width:1024,height:768},hasTouch:true,serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='error')errors.push(e.text());});
 await p.goto('http://127.0.0.1:8765/slime/?v=aurora-8');await p.waitForFunction(()=>!!window.__slime,{},{polling:100,timeout:90000}).catch(e=>{console.error('Startup errors:',errors);throw e;});await p.evaluate(()=>{__slime.reset();__slime.advance(.2);__slime.renderOnce();});
 await p.locator('#pet-button').click();const xy=await p.evaluate(()=>__slime.screen()),cdp=await c.newCDPSession(p),pt=(x,y)=>({x,y,id:1,radiusX:4,radiusY:4,force:1});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt(xy.x-35,xy.y)]});
 for(const dx of [-15,10,35,10,-15,-35,-15,10,35])await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[pt(xy.x+dx,xy.y)]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await p.evaluate(()=>__slime.state().count>=2));assert.equal(await p.evaluate(()=>__slime.state().held),false);
 assert.ok(await p.evaluate(()=>__slime.expression.ripples.value.some(x=>x.w>=0)));await p.screenshot({path:path.join(out,'pet.png')});console.log('PASS actual finger stroking, affection, ripple pool and release');
 async function choose(toy){await p.locator('#play-menu').click();await p.locator('[data-toy='+toy+']').click();await p.evaluate(()=>{__slime.advance(.1);__slime.renderOnce();});}
 async function toyPoint(kind){return p.evaluate(kind=>{const s=__slime,m=kind==='bubbles'?s.toys.bubbles[0]:s.toys.ball,v=m.position.clone().project(s.camera);return{x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight};},kind);}
 await choose('bubbles');let hit=await toyPoint('bubbles');await p.touchscreen.tap(hit.x,hit.y);assert.equal(await p.evaluate(()=>__slime.toys.state().hits),1);assert.equal(await p.evaluate(()=>__slime.toys.bubbles[0].visible),false);await p.screenshot({path:path.join(out,'bubbles.png')});
 await choose('ball');hit=await toyPoint('ball');await p.touchscreen.tap(hit.x,hit.y);assert.ok(await p.evaluate(()=>__slime.toys.state().hits>=1));
 await choose('trampoline');await p.evaluate(()=>__slime.advance(1));assert.ok(await p.evaluate(()=>__slime.toys.state().hits>0));console.log('PASS all three toys, ray-hit bubbles and ball, trampoline bounce');
 await p.locator('#play-menu').click();await p.locator('#friend-name').fill('재이의 말랑이');await p.locator('#name-form button').click();await p.locator('#room-close').click();
 await p.evaluate(()=>{const now=performance.now()/1000+1000;for(let i=0;i<16;i++)__slime.friend.reward(now+i);});await p.locator('#play-menu').click();await p.locator('[data-ornament=hat]').click();await p.locator('#palette button').nth(2).click();await p.evaluate(()=>{__slime.advance(.3);__slime.renderOnce();});await p.screenshot({path:path.join(out,'hat.png')});
 await p.reload();await p.waitForFunction(()=>!!window.__slime,{},{polling:100,timeout:90000});assert.equal(await p.evaluate(()=>__slime.friend.data.name),'재이의 말랑이');assert.equal(await p.evaluate(()=>__slime.friend.data.ornament),'hat');assert.equal(await p.evaluate(()=>__slime.state().flavor),'mint');
 const saved=await p.evaluate(()=>({...__slime.friend.data}));await p.evaluate(()=>__slime.reset());assert.deepEqual(await p.evaluate(()=>__slime.friend.data),saved);assert.equal(await p.evaluate(()=>__slime.state().count),0);assert.equal(await p.evaluate(()=>__slime.toys.state().mode),'none');console.log('PASS saved name, color, costume; reset preserves earned gifts');
 for(const viewport of [{width:768,height:1024},{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(viewport);await p.evaluate(()=>{dispatchEvent(new Event('resize'));__slime.reset();__slime.renderOnce();});await p.locator('#play-menu').click();
 assert.ok(await p.locator('#playroom').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));await p.locator('#room-close').click();await p.screenshot({path:path.join(out,'layout-'+viewport.width+'.png')});}
 await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>__slime.advance(.05));assert.equal(await p.evaluate(()=>__slime.expression.rippleStrength.value),0);assert.deepEqual(errors,[]);console.log('PASS portrait/landscape controls, reduced motion, no shader errors');console.log('Screenshots: '+out);
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
