// 「오늘도 우리 집」 에피소드 대본.
// 컷(panel) 하나 = 배경(bg) + 뒤 소품(bp) + 인물(chars) + 앞 소품(fp) + 말풍선(b) + 효과음(sfx) + 내레이션(n, n2).
// 좌표는 폭 400 기준. 인물의 y 를 비우면 바닥선(높이 - 24)에 선다.
// 말풍선 k: 없으면 보통, "shout" 외침, "think" 생각, "whisper" 속삭임. tail: 꼬리 방향(b, bl, br, t, tl, tr, l, r, 빈 값).
(function (root) {
  "use strict";

  // 얼굴 가운데 높이(발 기준). art.js 의 CHARS.headY 와 같다.
  const HEAD_Y = { jaei: -157, taeo: -126, eomma: -216, appa: -224, halmeoni: -209, harabeoji: -219 };
  const C = (c, x, e, p, more) => ({ c, x, e, p, ...more });
  // 가슴 위 클로즈업: 얼굴 가운데를 (x, hy) 에 두고 s 배로 키운다.
  const bust = (c, x, hy, s, e, p, more) => ({ c, x, e, p, s, y: Math.round(hy - HEAD_Y[c] * s * 0.98), ...more });
  const B = (t, x, y, tail, more) => ({ t, x, y, tail, ...more });
  const FX = (t, x, y, more) => ({ t, x, y, ...more });

  const CHARACTERS = [
    { id: "jaei", name: "재이", tag: "초등학생 · 참을성 만렙 누나", line: "동생이 아무리 괴롭혀도 참고 또 참는 누나. 태오가 혼나면 제일 먼저 달려가 안아 줘요. 하지만 참다 참다 폭발하면… “김태오!” 엉덩이 찰싹! 그림 그리기를 제일 좋아해요.", pose: "wave", e: "happy" },
    { id: "halmeoni", name: "할머니", tag: "뽀글 파마 · 우리 집 따뜻한 품", line: "무엇이든 “괜찮다, 괜찮다” 해 주는 사람. 할머니 앞치마 주머니엔 언제나 사탕이 있어요. 아빠를 “김서방~” 하고 불러요.", pose: "stand", e: "smile" },
    { id: "eomma", name: "엄마", tag: "똥머리 · 우리 집 CCTV급 눈썰미", line: "화나면 제일 무섭지만, 제일 먼저 안아 주는 사람. 엄마는 늘 가장 작은 조각을 가져가요.", pose: "stand", e: "smile" },
    { id: "appa", name: "아빠", tag: "퇴근하면 소파와 한 몸", line: "아재개그 담당, 목말 태우기 전문. 방귀는 아빠가 원조라는 소문이 있어요.", pose: "wave", e: "happy" },
    { id: "harabeoji", name: "할아버지", tag: "짙은 눈썹 · 반짝이는 머리", line: "말수는 적지만 손주들 앞에선 늘 허허 웃는 사람. 요즘 스마트폰 공부 중이에요.", pose: "stand", e: "proud" },
    { id: "taeo", name: "태오", tag: "태권도 파란띠 · 누나 괴롭히기 선수", line: "누나 괴롭히기가 취미인 막내(사실은 누나가 좋아서). 혼자 노는 것 같아도 가족 말을 다 듣고 있고, 틀려도 일단 소리 지르며 우기다가 들키면 머리를 긁적긁적. “맛있는 거 죠!”가 입버릇이고, 어벤져스 영웅도 태오식으로 불러요(블루베리, 쉬터맨, 스테잌로저…). 블랙 위도우랑 수가 제일 예쁘대요.", pose: "fist", e: "happy" },
  ];

  const EPISODES = [
    // ───────────────────────── 1화 ─────────────────────────
    {
      id: 1,
      title: "마지막 딸기 한 알",
      summary: "접시에 남은 딸기는 단 한 알. 가위바위보로 이긴 태오는 딸기를 입에 넣으려다 멈추는데…",
      lesson: "나누면 작아지는 게 아니라, 마음이 커져요.",
      talk: "우리 가족 중에 나에게 가장 많이 양보해 준 사람은 누구일까요?",
      cover: 7,
      panels: [
        {
          h: 330, bg: "kitchen",
          chars: [C("appa", 60, "happy", "stand", { y: 330 }), C("taeo", 155, "love", "cheer", { y: 270 }), C("jaei", 250, "happy", "stand", { y: 280 }), C("eomma", 345, "smile", "stand", { y: 330 })],
          fp: [["table", 200, 240, { w: 400 }], ["plate", 200, 246, { n: 8 }]],
          n: "일요일 저녁, 우리 집 식탁.",
          b: [B("딸기다아아!", 150, 64, "b", { k: "shout" })],
        },
        {
          h: 250, bg: "burst:ffe27a",
          fp: [["plate", 200, 170, { n: 1, r: 90, bs: 2.2 }], ["sparkle", 150, 90, { s: 1.4 }], ["sparkle", 262, 110, { s: 1 }]],
          n: "그리고… 남은 딸기는 딱 한 알.",
          sfx: [FX("반짝", 300, 70, { rot: 10, c: "#ff6b6b" })],
        },
        {
          h: 330, bg: "kitchen",
          chars: [bust("appa", 110, 150, 1.25, "sly", "give"), bust("jaei", 300, 170, 1.25, "sly", "stand")],
          fp: [["table", 200, 290, { w: 400 }], ["plate", 205, 296, { n: 1 }]],
          b: [B("음~ 아빠는 배불러서 괜찮은데~", 120, 44, "b", { w: 200 }), B("…아빠 손은 왜 딸기 쪽으로 가?", 290, 60, "b", { w: 150 })],
        },
        {
          h: 280, bg: "burst:c9dcff",
          chars: [bust("appa", 130, 130, 1.4, "shock", "give")],
          b: [B("여보.", 330, 70, "r", { k: "whisper" })],
          sfx: [FX("움찔!", 250, 200, { rot: -8, c: "#3b6fd6" })],
        },
        {
          h: 320, bg: "kitchen",
          chars: [C("taeo", 130, "determined", "cheer", { y: 290 }), C("jaei", 280, "happy", "fist", { y: 296 })],
          fp: [["table", 200, 262, { w: 400 }]],
          b: [B("그럼 가위바위보 하자!!", 130, 50, "b", { k: "shout" }), B("좋아! 딱 한 판이야!", 300, 80, "bl")],
        },
        {
          h: 300, bg: "speed:fff3f6",
          chars: [C("appa", 55, "determined", "kick", { s: 0.8 }), C("eomma", 150, "determined", "fist", { s: 0.8 }), C("jaei", 250, "determined", "cheer", { s: 0.95 }), C("taeo", 340, "determined", "kick", { s: 1 })],
          sfx: [FX("가위!", 90, 50, { rot: -10, c: "#ff6b6b" }), FX("바위!", 200, 38, { rot: 4, c: "#3b6fd6" }), FX("보!!", 320, 56, { rot: 10, c: "#2fbf5b", size: 1.4 })],
        },
        {
          h: 320, bg: "burst:ffd1e1",
          chars: [C("appa", 60, "shock", "stand", { s: 0.85 }), C("taeo", 200, "laugh", "up", { s: 1.3 }), C("jaei", 340, "sad", "stand", { s: 0.95 })],
          b: [B("이겼다아아아!", 200, 44, "b", { k: "shout" })],
          sfx: [FX("와아", 70, 70, { rot: -12, c: "#ff9f1c", size: 0.9 })],
        },
        {
          h: 380, bg: "kitchen",
          chars: [bust("taeo", 200, 190, 1.9, "smile", "hold")],
          fp: [["berry", 200, 322, { s: 1.6 }]],
          n: "태오는 딸기를 입에 넣으려다… 멈췄다.",
          b: [B("…그런데.", 90, 110, "br", { k: "think" })],
        },
        {
          h: 330, bg: "sparkle:fff0d6",
          chars: [bust("eomma", 200, 160, 1.4, "smile", "stand")],
          n: "엄마는 오늘 딸기를 한 알도 안 먹었다.",
          n2: "우리가 먹는 걸, 가만히 보고만 있었다.",
        },
        {
          h: 360, bg: "kitchen",
          chars: [C("taeo", 120, "happy", "give", { y: 318 }), C("eomma", 290, "surprised", "stand", { y: 360 })],
          fp: [["table", 200, 300, { w: 400 }], ["berry", 187, 244, { s: 0.9 }]],
          b: [B("엄마! 아~ 해!", 110, 70, "b", { k: "shout" }), B("어머, 엄마는 너희 먹는 것만 봐도 배불러~", 300, 70, "b", { w: 170 })],
        },
        {
          h: 300, bg: "burst:ffe27a",
          chars: [bust("taeo", 120, 140, 1.4, "angry", "hip"), bust("eomma", 310, 160, 1.3, "shy", "cover")],
          b: [B("거짓말! 엄마 배에서 방금 꼬르륵 했어!", 190, 36, "bl", { w: 290, k: "shout" })],
          sfx: [FX("꼬르륵~", 300, 270, { rot: -6, c: "#b0582a" })],
        },
        {
          h: 330, bg: "kitchen",
          chars: [C("jaei", 70, "happy", "point", { y: 300 }), C("appa", 290, "proud", "hip", { y: 340 })],
          fp: [["table", 200, 270, { w: 400 }], ["plate", 190, 276, { n: 1 }]],
          b: [B("그럼 넷으로 나누자!", 80, 60, "b"), B("좋아, 아빠가 공평하게 잘라 줄게!", 300, 50, "b", { w: 170 })],
        },
        {
          h: 260, bg: "burst:dff3e4",
          fp: [["plate", 200, 170, { r: 110, cut: true }]],
          b: [B("아빠… 이게 공평해?", 100, 60, "r", { w: 150 })],
          sfx: [FX("…?", 320, 70, { rot: 8, c: "#4a3a33" })],
        },
        {
          h: 340, bg: "kitchen",
          chars: [C("taeo", 60, "sly", "stand", { y: 312 }), C("jaei", 150, "sly", "hip", { y: 316 }), C("appa", 265, "guilty", "give", { y: 352 }), C("eomma", 360, "surprised", "stand", { y: 352 })],
          fp: [["table", 200, 282, { w: 400 }]],
          b: [B("제일 큰 건 당연히…", 120, 44, "br"), B("…엄마 거지!", 300, 56, "bl", { k: "shout" })],
          sfx: [FX("째릿", 70, 130, { rot: -10, c: "#e0443e", size: 0.9 })],
        },
        {
          h: 400, bg: "sparkle:ffe3ee",
          chars: [C("appa", 60, "laugh", "stand", { y: 400 }), C("taeo", 155, "eating", "mouth", { y: 340 }), C("jaei", 250, "eating", "mouth", { y: 346 }), C("eomma", 345, "teary", "cheeks", { y: 400 })],
          fp: [["table", 200, 330, { w: 400 }], ["heart", 200, 60, { s: 1.4 }], ["heart", 120, 90, { s: 0.8 }], ["heart", 290, 96, { s: 0.9 }]],
          n: "딸기 한 알을 넷이 나눠 먹었는데,",
          n2: "이상하게 한 바구니 먹은 것보다 더 달았다.",
          sfx: [FX("하하하", 70, 120, { rot: -8, c: "#ff9f1c", size: 0.8 })],
        },
      ],
    },

    // ───────────────────────── 2화 ─────────────────────────
    {
      id: 2,
      title: "누나는 다 알아",
      summary: "누나가 학원 간 사이, 태오는 누나가 제일 아끼는 그림에 우유를 쏟고 말았다. 숨기면 없던 일이 될까?",
      lesson: "잘못을 말하는 건, 잘못보다 훨씬 큰 용기예요.",
      talk: "솔직하게 말하고 나서 마음이 가벼워졌던 적이 있나요?",
      cover: 10,
      panels: [
        {
          h: 330, bg: "living",
          bp: [["drawing", 290, 250, { s: 0.9 }], ["cup", 330, 270, {}]],
          chars: [C("taeo", 120, "determined", "kick", { o: "dobok", rot: -8 })],
          n: "토요일 오후. 누나가 학원에 간 사이.",
          sfx: [FX("얍!", 60, 90, { rot: -12, c: "#3b6fd6", size: 1.2 })],
        },
        {
          h: 250, bg: "burst:fff6c7",
          fp: [["drawing", 200, 150, { s: 1.8, rot: -4 }], ["cup", 290, 70, { tip: 130 }], ["splash", 210, 140, { s: 1.4 }]],
          sfx: [FX("철퍽!", 90, 60, { rot: -10, c: "#3b6fd6", size: 1.4 })],
        },
        {
          h: 320, bg: "living",
          chars: [C("taeo", 110, "shock", "cover", { o: "dobok" })],
          fp: [["drawing", 290, 270, { s: 1.1, v: "stain" }]],
          b: [B("누나가 제일 아끼는 가족 그림인데…", 270, 70, "bl", { k: "think", w: 160 })],
        },
        {
          h: 270, bg: "gloom",
          chars: [bust("taeo", 200, 140, 1.6, "cry", "eyes", { o: "dobok" })],
          b: [B("어… 어떡하지…", 200, 40, "b")],
        },
        {
          h: 340, bg: "living",
          bp: [["sofa", 230, 316, { w: 280 }]],
          chars: [C("taeo", 110, "sly", "hold", { o: "dobok" })],
          fp: [["drawing", 190, 270, { s: 0.6, rot: 70 }]],
          b: [B("안 보이면… 없는 거야.", 110, 70, "b", { k: "whisper" })],
          sfx: [FX("슥슥", 270, 170, { rot: 8, c: "#8a6d52" })],
        },
        {
          h: 340, bg: "entrance",
          bp: [["opendoor", 100, 316, {}], ["shoes", 250, 316, {}]],
          chars: [C("jaei", 100, "smile", "wave"), C("taeo", 290, "happy", "hold", { o: "dobok" })],
          b: [B("다녀왔습니다~", 100, 60, "b"), B("누나아~ 오늘 진짜 예쁘다! 가방 들어 줄까?", 290, 80, "b", { w: 160 })],
          sfx: [FX("반짝반짝", 290, 330, { rot: -6, c: "#ff9f1c", size: 0.7 })],
        },
        {
          h: 260, bg: "sparkle:e6e0ff",
          chars: [bust("jaei", 200, 140, 1.6, "sly", "think")],
          b: [B("…수상해.", 320, 60, "bl", { k: "think" })],
        },
        {
          h: 360, bg: "kitchen",
          chars: [C("appa", 60, "worried", "stand", { y: 360 }), C("taeo", 165, "guilty", "stand", { y: 300 }), C("eomma", 330, "surprised", "stand", { y: 360 })],
          fp: [["table", 200, 290, { w: 400 }], ["plate", 170, 296, { r: 36 }]],
          b: [B("태오야, 좋아하는 계란말이인데 왜 안 먹어?", 320, 44, "b", { w: 150 }), B("배… 배가 안 고파…", 180, 112, "b", { w: 120 }), B("(태오가 밥을 남기다니… 큰일이다)", 70, 50, "b", { k: "whisper", w: 120 })],
        },
        {
          h: 330, bg: "bedroom-night",
          bp: [["bed", 200, 310, { w: 330 }], ["pillow", 90, 250, {}]],
          chars: [C("taeo", 195, "worried", "stand", { o: "pajama", rot: -90, y: 262, s: 0.95 })],
          fp: [["blanket", 215, 296, { w: 190, h: 56, c: "#bfe3ff" }]],
          n: "그날 밤, 태오는 잠이 오지 않았다.",
          sfx: [FX("콩닥 콩닥", 270, 110, { rot: -6, c: "#ff5c7c" })],
        },
        {
          h: 380, bg: "bedroom-night",
          chars: [C("taeo", 110, "teary", "hold", { o: "pajama" }), C("jaei", 290, "surprised", "stand", { o: "pajama" })],
          fp: [["drawing", 112, 318, { s: 0.55, v: "stain" }]],
          b: [B("누나… 사실은… 내가 누나 그림에 우유 쏟았어.", 120, 60, "b", { w: 170 }), B("미안해…", 130, 150, "b", { k: "whisper" })],
        },
        {
          h: 320, bg: "sparkle:ffe3ee",
          chars: [bust("jaei", 120, 170, 1.4, "smile", "stand", { o: "pajama" }), bust("taeo", 300, 190, 1.4, "surprised", "stand", { o: "pajama" })],
          b: [B("알고 있었어.", 120, 50, "b"), B("에엣?!", 310, 70, "b", { k: "shout" })],
        },
        {
          h: 350, bg: "bedroom-night",
          chars: [C("jaei", 110, "wink", "point", { o: "pajama" }), C("taeo", 300, "shock", "stand", { o: "pajama" })],
          b: [B("소파 밑으로 그림 끝이 삐죽 나와 있었거든.", 110, 60, "b", { w: 170 })],
          sfx: [FX("들켰다!", 300, 70, { rot: 8, c: "#e0443e" })],
        },
        {
          h: 360, bg: "sparkle:fff0d6",
          chars: [C("taeo", 255, "cry", "hug", { o: "pajama" }), C("jaei", 150, "teary", "hug", { o: "pajama" })],
          fp: [["heart", 200, 90, { s: 1.2 }]],
          b: [B("네가 먼저 말해 주길 기다렸어. 말해 줘서 고마워.", 200, 30, "", { w: 250 })],
          n2: "누나는 다 안다. 그리고… 다 안아 준다.",
        },
        {
          h: 330, bg: "bedroom-night",
          chars: [C("jaei", 110, "happy", "point", { o: "pajama" }), C("taeo", 290, "laugh", "cheer", { o: "pajama" })],
          b: [B("그림은 다시 그리면 돼. 이번엔 같이 그리자!", 110, 60, "b", { w: 160 }), B("응!! 공룡도 넣을래!", 300, 70, "b")],
        },
        {
          h: 400, bg: "living",
          bp: [["drawing", 215, 100, { s: 0.9, v: "new" }]],
          chars: [C("appa", 80, "guilty", "scratch"), C("eomma", 300, "sly", "hip")],
          n: "다음 날.",
          b: [B("여보… 사실 나도 고백할 게 있는데… 어제 당신 화분…", 90, 60, "b", { w: 160 }), B("알고 있었어.", 330, 62, "b", { k: "whisper" })],
          sfx: [FX("쿵!", 170, 250, { rot: -10, c: "#3b6fd6", size: 1.3 })],
        },
      ],
    },

    // ───────────────────────── 3화 ─────────────────────────
    {
      id: 3,
      title: "아빠 충전소",
      summary: "퇴근한 아빠는 소파에 눕자마자 잠들어 버렸다. 재이와 태오가 차린 ‘아빠 충전소’, 과연 영업 성공?",
      lesson: "사랑은 받기만 하는 게 아니라, 돌려주는 거예요.",
      talk: "오늘 가족에게 줄 수 있는 나만의 ‘쿠폰’을 만들어 볼까요?",
      cover: 11,
      panels: [
        {
          h: 340, bg: "street",
          chars: [C("appa", 150, "sleepy", "stand", { o: "work", tilt: -8 })],
          fp: [["briefcase", 205, 250, {}], ["battery", 310, 90, { lv: 1, s: 1.1 }]],
          n: "평일 저녁 7시. 아빠의 배터리는…",
          sfx: [FX("3%", 310, 140, { c: "#ff4d4d", size: 0.9 })],
        },
        {
          h: 360, bg: "entrance:evening",
          bp: [["opendoor", 90, 336, {}]],
          chars: [C("appa", 90, "happy", "stand", { o: "work" }), C("taeo", 230, "laugh", "up"), C("jaei", 330, "happy", "cheer")],
          b: [B("아빠다아아!", 240, 44, "bl", { k: "shout" }), B("아빠 목말 태워 줘!", 345, 112, "b", { w: 110 }), B("공룡 놀이도 해!", 200, 140, "b", { w: 100 })],
        },
        {
          h: 330, bg: "living",
          bp: [["sofa", 200, 306, { w: 320 }]],
          chars: [C("appa", 320, "sleepy", "stand", { o: "work", rot: -90, x: 330, y: 226, s: 0.85 })],
          fp: [["sofafront", 200, 306, { w: 320 }]],
          b: [B("5분만… 딱 5분만…", 110, 90, "b", { k: "whisper" })],
          sfx: [FX("Zzz", 120, 170, { rot: -10, c: "#6c8fd6" })],
        },
        {
          h: 330, bg: "living",
          chars: [C("taeo", 90, "sad", "stand"), C("jaei", 190, "worried", "stand"), C("eomma", 320, "smile", "mouth")],
          b: [B("아빠 또 잔다…", 90, 90, "b"), B("쉿, 아빠 오늘 회사에서 많이 힘드셨대.", 310, 40, "b", { k: "whisper", w: 150 })],
        },
        {
          h: 300, bg: "sparkle:fff3c4",
          chars: [bust("jaei", 110, 150, 1.35, "proud", "fist"), bust("taeo", 300, 170, 1.3, "surprised", "stand")],
          fp: [["sparkle", 60, 60, { s: 1.2 }]],
          b: [B("태오야, 우리가 아빠를 충전해 주자!", 130, 40, "b", { w: 160 }), B("충전? 아빠가 핸드폰이야?", 300, 60, "b", { w: 120 })],
        },
        {
          h: 240, bg: "burst:ffe27a",
          fp: [["sign", 200, 120, { t: "♥ 아빠 충전소 OPEN ♥", w: 280, fs: 26 }]],
          sfx: [FX("짜잔!", 330, 50, { rot: 10, c: "#ff6b6b" })],
        },
        {
          h: 340, bg: "living",
          bp: [["sofa", 200, 316, { w: 320 }]],
          chars: [C("appa", 320, "sleepy", "stand", { o: "work", rot: -90, x: 330, y: 236, s: 0.85 }), C("taeo", 240, "determined", "cheer", { o: "dobok", y: 250, s: 0.9 })],
          fp: [["sofafront", 200, 316, { w: 320 }]],
          b: [B("태권도 안마 시작합니다! 얍! 얍!", 150, 40, "br", { w: 170 }), B("으음… 시원하다…", 90, 160, "b", { k: "whisper", w: 110 })],
          sfx: [FX("콩! 콩!", 330, 190, { rot: 8, c: "#3b6fd6" })],
        },
        {
          h: 330, bg: "living",
          chars: [C("jaei", 110, "happy", "give")],
          fp: [["coupon", 270, 200, { s: 1.2 }]],
          b: [B("이건 쿠폰! 아빠가 쓰면 우리가 조용히 해 줄게!", 130, 50, "b", { w: 170 })],
        },
        {
          h: 330, bg: "living",
          bp: [["sofa", 200, 306, { w: 320 }]],
          chars: [C("appa", 320, "sleepy", "stand", { o: "work", rot: -90, x: 330, y: 226, s: 0.85 })],
          fp: [["sofafront", 200, 306, { w: 320 }], ["blanket", 230, 256, { w: 200, h: 44, c: "#ffcf6e" }], ["dino", 70, 318, { s: 1.1 }]],
          b: [B("공룡이 지켜 줄 거야.", 90, 80, "b", { k: "whisper" })],
        },
        {
          h: 280, bg: "burst:e8f7c8",
          chars: [bust("taeo", 110, 150, 1.4, "shock", "nose"), bust("jaei", 300, 150, 1.4, "laugh", "nose")],
          sfx: [FX("뿌우웅~~", 200, 50, { rot: -6, c: "#8a6d52", size: 1.5 })],
          b: [B("아빠 방귀 충전 완료!!", 150, 250, "tl", { k: "shout", w: 240 })],
        },
        {
          h: 330, bg: "living",
          chars: [C("appa", 110, "shy", "scratch", { o: "work" }), C("taeo", 250, "laugh", "cheer"), C("jaei", 340, "laugh", "cover")],
          b: [B("어… 아빠가 뭐 했니?", 100, 40, "b")],
          sfx: [FX("하하하하", 300, 70, { rot: 8, c: "#ff9f1c" })],
        },
        {
          h: 360, bg: "sparkle:ffe3ee",
          chars: [C("taeo", 110, "happy", "hug"), C("appa", 200, "teary", "hug", { o: "work" }), C("jaei", 300, "happy", "hug")],
          fp: [["coupon", 200, 250, { s: 0.8, rot: 4 }], ["heart", 330, 70, {}]],
          b: [B("아빠 배터리… 100% 충전됐다.", 200, 30, "", { w: 220 })],
        },
        {
          h: 420, bg: "living-night",
          chars: [C("taeo", 200, "laugh", "up", { y: 214, s: 0.9 }), C("appa", 200, "happy", "hold", { o: "work", s: 0.95 }), C("jaei", 320, "happy", "cheer")],
          fp: [["battery", 70, 90, { lv: 4 }]],
          b: [B("자, 이제 공룡 놀이 할 사람!", 100, 190, "r", { w: 110 }), B("저요!!", 335, 150, "b", { k: "shout" })],
          n2: "그날 밤, 우리 집 충전소는 늦게까지 불이 켜져 있었다.",
        },
      ],
    },

    // ───────────────────────── 4화 ─────────────────────────
    {
      id: 4,
      title: "엄마가 아픈 날",
      summary: "엄마가 감기로 누운 날, 아빠와 재이·태오가 ‘엄마 대신 작전’에 나섰다. 계란은 타고, 셔츠는 분홍색이 되고…",
      lesson: "당연한 하루는, 누군가의 사랑으로 만들어져요.",
      talk: "엄마(또는 가족)의 하루 중 내가 몰랐던 일은 무엇일까요?",
      cover: 11,
      panels: [
        {
          h: 330, bg: "bedroom",
          bp: [["bed", 200, 306, { w: 340 }], ["pillow", 90, 242, {}]],
          chars: [C("eomma", 300, "sick", "stand", { o: "sick", rot: -90, y: 256, s: 0.8 })],
          fp: [["blanket", 272, 292, { w: 210, h: 60, c: "#f7b9ca" }], ["towel", 112, 256, { rot: -90 }], ["thermo", 176, 262, { rot: 100 }]],
          n: "아침부터 엄마가 끙끙 앓았다.",
          b: [B("콜록… 오늘은… 좀 누워 있을게…", 280, 70, "bl", { w: 150 })],
        },
        {
          h: 360, bg: "living",
          chars: [C("taeo", 70, "determined", "fist"), C("appa", 200, "proud", "hip", { o: "apron" }), C("jaei", 330, "determined", "fist")],
          b: [B("걱정 마! 오늘은 우리가 엄마 대신이다!", 200, 48, "b", { w: 250, k: "shout" }), B("와아!", 60, 180, "b"), B("작전 개시!", 340, 190, "b")],
        },
        {
          h: 330, bg: "kitchen",
          chars: [C("appa", 150, "determined", "hold", { o: "apron" })],
          fp: [["pan", 175, 200, { s: 1.2 }]],
          n: "작전 1. 아침밥 만들기",
          sfx: [FX("치이익", 320, 150, { rot: 8, c: "#ff6b6b" })],
        },
        {
          h: 250, bg: "burst:d8d8d8",
          fp: [["smoke", 250, 110, { s: 1.2 }], ["pan", 190, 180, { burnt: true, s: 2 }]],
          sfx: [FX("탔다…", 100, 70, { rot: -10, c: "#4a3a33", size: 1.3 })],
        },
        {
          h: 320, bg: "kitchen",
          chars: [C("jaei", 90, "blank", "stand"), C("appa", 220, "guilty", "scratch", { o: "apron" }), C("taeo", 340, "happy", "cheer")],
          b: [B("아빠… 이건 계란이야, 숯이야?", 90, 50, "b", { w: 130 }), B("나 까만 거 좋아!", 330, 70, "b", { w: 100 })],
        },
        {
          h: 330, bg: "living",
          chars: [C("appa", 110, "smile", "carry", { o: "apron" }), C("taeo", 290, "happy", "give")],
          fp: [["basket", 110, 260, {}], ["sock", 250, 200, { rot: 40 }]],
          n: "작전 2. 빨래하기",
          b: [B("내 빨간 양말도 같이 넣어야지~", 300, 90, "b", { w: 130 })],
          sfx: [FX("쏙", 210, 180, { c: "#e8344a" })],
        },
        {
          h: 300, bg: "burst:ffc4d8",
          chars: [bust("appa", 200, 110, 1.3, "shock", "hands", { o: "apron" })],
          fp: [["shirt", 200, 250, { c: "#f7a3c0", s: 1.4 }]],
          b: [B("내 흰 셔츠가…!!", 330, 60, "bl", { k: "shout", w: 110 })],
          sfx: [FX("분홍분홍", 80, 240, { rot: -10, c: "#f0609d" })],
        },
        {
          h: 350, bg: "living",
          chars: [C("taeo", 100, "sad", "carry"), C("jaei", 280, "worried", "carry")],
          fp: [["toys", 200, 330, {}]],
          n: "작전 3. 장난감 정리",
          b: [B("엄마는 이걸 매일 해?", 100, 100, "b"), B("매일… 거기에 밥이랑, 빨래랑…", 280, 110, "b", { w: 130 })],
        },
        {
          h: 170, bg: "sparkle:fff0d6",
          fp: [["heart", 340, 110, { s: 0.9 }]],
          n: "처음 알았다.",
          n2: "엄마의 하루가 얼마나 바빴는지.",
        },
        {
          h: 340, bg: "kitchen",
          chars: [C("appa", 70, "smile", "hold", { o: "apron" }), C("jaei", 205, "determined", "hold"), C("taeo", 330, "proud", "give", { f: -1 })],
          fp: [["bowl", 205, 262, { s: 1.1, steam: false }], ["salt", 262, 226, { rot: -150 }], ["grains", 232, 236, {}]],
          n: "작전 4. 엄마를 위한 죽",
          b: [B("소금은 조금만~", 330, 60, "b")],
          sfx: [FX("와르르", 250, 318, { rot: 10, c: "#6c8fd6", size: 0.8 })],
        },
        {
          h: 380, bg: "bedroom",
          bp: [["bed", 200, 356, { w: 360 }]],
          chars: [bust("eomma", 200, 150, 1.05, "surprised", "stand", { o: "sick" }), C("jaei", 58, "happy", "hold"), C("taeo", 348, "happy", "wave")],
          fp: [["blanket", 200, 350, { w: 210, h: 80, c: "#f7b9ca" }], ["bowl", 58, 300, { s: 0.8, steam: false }]],
          b: [B("엄마! 우리가 만든 죽이에요!", 90, 50, "b", { w: 140 })],
        },
        {
          h: 320, bg: "sparkle:fff0d6",
          chars: [bust("eomma", 200, 160, 1.6, "eating", "mouth", { o: "sick" })],
          b: [B("(…짜다…!)", 330, 60, "bl", { k: "think" })],
          sfx: [FX("짭짤", 70, 80, { rot: -12, c: "#6c8fd6" })],
        },
        {
          h: 330, bg: "sparkle:ffe3ee",
          chars: [bust("eomma", 200, 160, 1.4, "teary", "stand", { o: "sick" })],
          b: [B("음… 세상에서 제일 맛있는 죽이다.", 200, 40, "", { w: 220 })],
        },
        {
          h: 360, bg: "bedroom",
          chars: [C("taeo", 90, "teary", "stand"), C("jaei", 310, "teary", "stand")],
          b: [B("엄마, 매일 우리 밥 해 줘서 고마워요.", 90, 60, "b", { w: 130 }), B("빨래도, 정리도… 다 고마워요.", 310, 90, "b", { w: 130 })],
        },
        {
          h: 360, bg: "sparkle:ffe3ee",
          chars: [C("taeo", 110, "cry", "hug"), C("eomma", 200, "teary", "hug", { o: "sick" }), C("jaei", 290, "cry", "hug")],
          fp: [["heart", 90, 80, {}], ["heart", 320, 60, { s: 1.2 }]],
          b: [B("엄마… 벌써 다 나은 것 같아.", 200, 30, "", { w: 210 })],
        },
        {
          h: 400, bg: "entrance",
          bp: [["door", 90, 376, {}]],
          chars: [C("appa", 110, "proud", "wave", { o: "pink" }), C("eomma", 240, "laugh", "cover"), C("taeo", 340, "laugh", "point")],
          fp: [["briefcase", 60, 330, {}]],
          n: "다음 날 아침.",
          b: [B("오늘은… 이 셔츠가 입고 싶었어.", 130, 88, "b", { w: 190 })],
          n2: "아빠는 분홍 셔츠를 입고 출근했다.",
          sfx: [FX("뿌듯", 330, 110, { rot: 10, c: "#f0609d" })],
        },
      ],
    },

    // ───────────────────────── 5화 ─────────────────────────
    {
      id: 5,
      title: "할아버지의 영상통화",
      summary: "스마트폰 영상통화를 배우고 싶은 할아버지. 재이는 친절한 선생님이 되기로 했지만, 자꾸만 속이 터지는데…",
      lesson: "우리가 천천히 배울 때 기다려 준 사람들이 있어요. 이번엔 우리가 기다려 줄 차례예요.",
      talk: "내가 어렸을 때 가족이 참을성 있게 가르쳐 준 것은 무엇일까요?",
      cover: 12,
      panels: [
        {
          h: 400, bg: "halmae",
          chars: [C("harabeoji", 120, "worried", "hold"), C("jaei", 290, "proud", "hip")],
          fp: [["phone", 120, 262, { s: 0.9 }]],
          n: "주말, 할머니 할아버지 댁.",
          b: [B("재이야, 이 영상통화라는 거… 어떻게 하는 거냐?", 200, 80, "bl", { w: 250 }), B("제가 알려 드릴게요!", 330, 150, "b", { w: 130 })],
        },
        {
          h: 360, bg: "halmae",
          chars: [bust("harabeoji", 280, 190, 1.25, "surprised", "stand"), bust("jaei", 110, 210, 1.25, "smile", "point")],
          fp: [["phone", 205, 290, { s: 1.4, screen: "#c9f5c9" }]],
          b: [B("여기 초록 버튼 누르시고, 얼굴이 화면에 나오게 드시면 돼요!", 140, 50, "b", { w: 250 }), B("오호라.", 340, 90, "b")],
        },
        {
          h: 360, bg: "plain:bfe7ff",
          chars: [C("harabeoji", 200, "blank", "stand", { s: 3.6, y: 1150 })],
          fp: [["phoneframe", 0, 0, {}]],
          b: [B("할아버지! 머리만 보여요!", 200, 110, "", { k: "shout", w: 250 })],
          sfx: [FX("번쩍!", 300, 215, { rot: 10, c: "#ff9f1c", size: 1.2 })],
        },
        {
          h: 330, bg: "halmae",
          chars: [C("halmeoni", 80, "laugh", "cover"), C("harabeoji", 210, "shy", "scratch"), C("taeo", 340, "laugh", "point")],
          b: [B("허허, 요 녀석들.", 210, 40, "b")],
          sfx: [FX("깔깔깔", 330, 110, { rot: 8, c: "#ff9f1c" })],
        },
        {
          h: 380, bg: "halmae",
          chars: [C("harabeoji", 110, "worried", "hold"), C("jaei", 290, "angry", "hip")],
          fp: [["phone", 110, 242, { s: 0.9, screen: "#ffb3b3" }]],
          b: [B("할아버지! 아까 말씀드렸잖아요! 빨간 거 말고 초록 거요!", 230, 60, "br", { w: 290, k: "shout" })],
          sfx: [FX("뚝", 200, 270, { rot: -10, c: "#e0443e", size: 1.2 })],
        },
        {
          h: 280, bg: "plain:e9e6e1",
          chars: [bust("harabeoji", 200, 150, 1.5, "sad", "stand")],
          b: [B("…할아버지가 자꾸 까먹어서 미안하구나.", 200, 36, "", { w: 220 })],
        },
        {
          h: 360, bg: "halmae",
          chars: [C("halmeoni", 120, "smile", "stand", { o: "apron" }), C("jaei", 290, "guilty", "stand")],
          b: [B("재이야, 너 아기 때 숟가락질 누가 가르쳐 줬는지 아니?", 130, 50, "b", { w: 170 }), B("…?", 300, 150, "b")],
        },
        {
          h: 400, bg: "memory",
          chars: [C("harabeoji", 110, "happy", "give", { s: 0.95 }), C("jaei", 280, "eating", "stand", { s: 0.62 })],
          fp: [["spoonful", 256, 300, { rot: 205 }], ["grains", 300, 316, {}]],
          b: [B("옳지, 옳지~ 우리 재이 잘한다!", 150, 100, "bl", { w: 230 })],
          n: "백 번을 흘려도, 할아버지는 백 번 다 웃으셨지.",
        },
        {
          h: 350, bg: "halmae",
          chars: [bust("halmeoni", 110, 190, 1.2, "smile", "stand", { o: "apron" }), bust("jaei", 300, 210, 1.25, "teary", "stand")],
          b: [B("그때 할아버지는 한 번도 ‘아까 말했잖아’ 안 하셨단다.", 170, 50, "bl", { w: 280 })],
        },
        {
          h: 360, bg: "sparkle:fff0d6",
          chars: [C("jaei", 150, "teary", "hug"), C("harabeoji", 270, "teary", "hug")],
          fp: [["heart", 210, 80, {}]],
          b: [B("할아버지, 우리 천천히 다시 해 봐요. 백 번 해도 괜찮아요!", 180, 50, "bl", { w: 280 })],
        },
        {
          h: 330, bg: "halmae",
          chars: [C("taeo", 60, "happy", "cheer"), C("harabeoji", 200, "determined", "hold"), C("jaei", 330, "smile", "point")],
          fp: [["phone", 200, 222, { s: 0.9 }]],
          b: [B("할아버지 파이팅!", 70, 70, "b")],
          n2: "그리고 정말… 열한 번째에.",
        },
        {
          h: 230, bg: "burst:c8f5c8",
          fp: [["phone", 200, 120, { s: 2.2, screen: "#c9f5c9", face: "harabeoji" }]],
          sfx: [FX("띠리리링~", 90, 60, { rot: -10, c: "#2fbf5b" }), FX("연결됐다!!", 300, 190, { rot: 8, c: "#ff6b6b" })],
        },
        {
          h: 420, bg: "plain:bfe7ff",
          chars: [bust("harabeoji", 180, 220, 1.8, "laugh", "stand"), C("halmeoni", 330, "happy", "stand", { s: 2.4, y: 935 })],
          fp: [["phoneframe", 0, 0, {}]],
          b: [B("재이야! 할아버지다! 혼자 했다!", 200, 80, "b", { w: 250 }), B("할머니~ 파마만 보여요!", 130, 330, "", { k: "shout", w: 190 })],
        },
        {
          h: 380, bg: "bedroom-night",
          chars: [C("jaei", 150, "laugh", "hold", { o: "pajama" }), C("taeo", 280, "laugh", "cheer", { o: "pajama" })],
          fp: [["phone", 150, 256, { s: 0.8, face: "harabeoji" }], ["heart", 80, 90, {}]],
          n: "우리가 천천히 배울 때, 기다려 준 사람들이 있다.",
          n2: "이번엔 우리가 기다려 줄 차례다.",
        },
      ],
    },
    // ───────────────────────── 6화 ─────────────────────────
    {
      id: 6,
      title: "태오어 사전",
      summary: "블루베리, 스테잌로저, 우엉… 태오만의 말에 누나가 “다 틀렸어!”라고 소리치자, 태오는 입을 꾹 다물어 버렸다.",
      lesson: "틀린 말이 아니라, 지금만 들을 수 있는 보물 같은 말이에요.",
      talk: "우리 가족만 알아듣는 말이 있나요? 우리 집 사전을 만들어 볼까요?",
      cover: 6,
      panels: [
        {
          h: 340, bg: "halmae",
          chars: [C("taeo", 140, "determined", "kick")],
          fp: [["figures", 300, 316, { s: 1.3 }]],
          n: "막내 태오에게는 태오만의 말이 있다.",
          b: [B("블루베리! 출동!", 140, 92, "b", { k: "shout" })],
          sfx: [FX("슈웅", 320, 180, { rot: 8, c: "#3b6fd6" })],
        },
        {
          h: 280, bg: "burst:e6e0ff",
          chars: [bust("jaei", 200, 175, 1.3, "surprised", "stand")],
          b: [B("…블루베리?", 200, 40, "", { w: 200 })],
        },
        {
          h: 360, bg: "halmae",
          chars: [C("taeo", 110, "proud", "point"), C("jaei", 305, "blank", "stand")],
          fp: [["figures", 215, 336, { s: 0.9 }]],
          b: [B("블루베리 몰라? 까만 고양이 영웅! 지잔이랑 스테잌로저도 있어!", 130, 60, "b", { w: 230 })],
        },
        {
          h: 300, bg: "burst:ffe27a",
          chars: [bust("appa", 200, 170, 1.3, "laugh", "stand")],
          b: [B("스테잌…? 아빠 갑자기 배고파지네.", 200, 40, "", { w: 250 })],
          sfx: [FX("꼬르륵~", 320, 270, { rot: -6, c: "#b0582a" })],
        },
        {
          h: 340, bg: "halmae",
          chars: [C("taeo", 110, "proud", "hip"), C("jaei", 300, "sly", "think")],
          b: [B("그리고 대장은 미스테리야! 눈에 안대 한 사람!", 125, 60, "b", { w: 200 }), B("그건 닉 퓨리겠지…", 320, 70, "b", { k: "whisper", w: 110 })],
        },
        {
          h: 400, bg: "kitchen",
          chars: [C("taeo", 90, "smile", "stand"), C("halmeoni", 290, "smile", "give", { o: "apron", f: -1 })],
          fp: [["banchan", 212, 254, { s: 1.1 }]],
          b: [B("태오야, 할머니가 만든 우엉조림 먹어 보렴.", 260, 50, "b", { w: 240 })],
        },
        {
          h: 290, bg: "burst:c9dcff",
          chars: [bust("taeo", 200, 170, 1.5, "shock", "cheeks")],
          b: [B("우엉?! 우엉은 마법사잖아!!", 200, 40, "", { k: "shout", w: 280 })],
        },
        {
          h: 380, bg: "kitchen",
          chars: [C("harabeoji", 110, "laugh", "stand"), C("halmeoni", 290, "laugh", "cover", { o: "apron" })],
          b: [B("허허, 마법사 반찬이면 더 맛있겠구나.", 150, 44, "bl", { w: 230 })],
          sfx: [FX("깔깔깔", 205, 230, { rot: 8, c: "#ff9f1c" })],
        },
        {
          h: 380, bg: "halmae",
          chars: [C("taeo", 110, "surprised", "stand", { rot: -8 }), C("halmeoni", 290, "surprised", "stand")],
          b: [B("쓰구미!", 110, 120, "b", { k: "shout" }), B("쓰…구미?", 300, 50, "b")],
          sfx: [FX("쿵", 200, 250, { rot: -10, c: "#3b6fd6" })],
        },
        {
          h: 380, bg: "halmae",
          chars: [C("taeo", 110, "proud", "hip"), C("halmeoni", 290, "happy", "stand")],
          b: [B("영어야! ‘실례합니다’라는 뜻!", 120, 60, "b", { w: 170 }), B("아이고, 우리 태오 영어도 잘하네~", 300, 48, "b", { w: 170 })],
        },
        {
          h: 350, bg: "halmae",
          chars: [C("taeo", 110, "love", "point"), C("jaei", 300, "proud", "wave")],
          n: "저녁, 새 원피스를 입고 나온 누나.",
          b: [B("누나 블레이뽀!!", 120, 100, "b", { k: "shout" })],
          sfx: [FX("빙그르", 300, 330, { rot: -6, c: "#f0609d", size: 0.8 })],
        },
        {
          h: 370, bg: "halmae",
          chars: [C("taeo", 90, "worried", "stand"), C("jaei", 270, "angry", "hip")],
          b: [B("블레이뽀가 아니라 뷰티풀! 블루베리 아니고 블랙팬서! 지잔 아니고 비전! 다 틀렸어!", 235, 55, "bl", { k: "shout", w: 300 })],
        },
        {
          h: 280, bg: "gloom",
          chars: [bust("taeo", 200, 170, 1.5, "cry", "eyes")],
          b: [B("…나 이제 말 안 할래.", 200, 40, "", { w: 220 })],
        },
        {
          h: 300, bg: "halmae",
          chars: [bust("jaei", 200, 180, 1.3, "guilty", "stand")],
          n: "그날 저녁, 태오는 정말 조용했다.",
          n2: "누나는 그게 더 마음이 쓰였다.",
        },
        {
          h: 400, bg: "halmae",
          chars: [C("eomma", 110, "smile", "hold"), C("jaei", 305, "surprised", "stand")],
          fp: [["notebook", 110, 250, { t: "재이 말 모음", s: 0.6, c: "#ffb8d0", lines: ["짐방 = 김서방", ""] }]],
          b: [B("재이야, 이거 봐. 네가 어렸을 때 엄마가 적어 둔 ‘재이 말 모음’이야.", 150, 46, "bl", { w: 250 })],
        },
        {
          h: 420, bg: "memory",
          chars: [C("halmeoni", 90, "happy", "wave"), C("appa", 215, "surprised", "stand"), C("jaei", 330, "happy", "point", { s: 0.62, f: -1 })],
          n: "재이가 아기였을 때.",
          b: [B("김서방~ 왔는가!", 105, 96, "b", { w: 140 }), B("짐방!", 335, 232, "b", { k: "shout" })],
          sfx: [FX("짐…방?!", 280, 92, { rot: 8, c: "#3b6fd6", size: 0.8 })],
        },
        {
          h: 320, bg: "sparkle:ffe3ee",
          chars: [bust("jaei", 115, 190, 1.2, "shy", "cheeks"), bust("appa", 300, 200, 1.15, "laugh", "stand")],
          b: [B("내가… 아빠를 ‘짐방’이라고 불렀어?", 120, 50, "b", { w: 180 }), B("그래서 한동안 아빠 별명이 짐방이었지~", 300, 60, "b", { w: 160 })],
        },
        {
          h: 330, bg: "sparkle:fff0d6",
          chars: [bust("eomma", 200, 185, 1.25, "teary", "stand")],
          b: [B("이런 말은 지금만 들을 수 있는 보물이야. 조금 크면 다 바르게 말하게 되거든.", 200, 44, "", { w: 300 })],
        },
        {
          h: 360, bg: "halmae",
          chars: [C("jaei", 130, "teary", "give"), C("taeo", 305, "surprised", "stand")],
          fp: [["notebook", 205, 262, { t: "태오어 사전", s: 0.55, lines: ["", ""] }]],
          b: [B("태오야, 아까 미안해. 누나가 ‘태오어 사전’ 만들어 줄게!", 150, 56, "b", { w: 230 })],
        },
        {
          h: 370, bg: "halmae",
          chars: [C("taeo", 110, "laugh", "cheer"), C("jaei", 300, "laugh", "cover")],
          b: [B("진짜? 포도도 넣어 줘! 헬로키티도!", 120, 70, "b", { w: 190 }), B("그건 포비랑… 마이멜로디잖아!", 300, 60, "b", { w: 170 })],
        },
        {
          h: 380, bg: "sparkle:fff4c7",
          fp: [["notebook", 200, 205, { t: "태오어 사전", s: 2.2, lines: ["쓰구미 = 익스큐즈미", "블루베리 = 블랙팬서", "우엉 = 웡 (마법사)", "포도 = 포비"] }], ["heart", 340, 80, {}]],
          n: "오늘도 태오어 사전은 한 장씩 늘어난다.",
          n2: "언젠가 이 말들이 그리워질 테니까.",
        },
      ],
    },
    // ───────────────────────── 7화 ─────────────────────────
    {
      id: 7,
      title: "오늘 티비 보는 날이야?",
      summary: "월요일부터 금요일까지, 태오의 아침 질문은 늘 똑같다. “오늘 티비 보는 날이야? 어린이집 안 가는 날이야? 맛있는 거 죠!”",
      lesson: "아이가 매일 하는 말 속에는 ‘같이 있고 싶어’가 숨어 있어요.",
      talk: "우리 가족이 매일 하는 말은 뭘까요? 그 말 속에 숨은 마음은 무엇일까요?",
      cover: 3,
      panels: [
        {
          h: 360, bg: "bedroom",
          chars: [C("taeo", 130, "happy", "up", { o: "pajama" }), C("jaei", 300, "sleepy", "stand", { o: "pajama" })],
          n: "월요일 아침. 태오가 눈 뜨자마자 하는 말.",
          b: [B("오늘 티비 보는 날이야?", 140, 105, "b", { k: "shout", w: 210 })],
        },
        {
          h: 400, bg: "kitchen",
          chars: [C("taeo", 100, "sad", "stand", { o: "pajama" }), C("eomma", 290, "smile", "hold")],
          b: [B("아니~ 오늘은 어린이집 가는 날.", 290, 50, "b", { w: 170 }), B("그럼 어린이집 안 가는 날이야?", 110, 150, "b", { w: 170 })],
        },
        {
          h: 270, bg: "burst:dff3e4",
          chars: [bust("eomma", 200, 170, 1.2, "blank", "stand")],
          b: [B("…방금 가는 날이라고 했잖아.", 200, 40, "", { w: 260 })],
        },
        {
          h: 290, bg: "burst:ffe27a",
          chars: [bust("taeo", 200, 180, 1.45, "determined", "cheer", { o: "pajama" })],
          b: [B("그럼 맛있는 거 죠!", 200, 40, "", { k: "shout", w: 260 })],
        },
        {
          h: 260, bg: "speed:eef4ff",
          chars: [C("taeo", 150, "happy", "up", { o: "pajama", s: 0.8 })],
          n: "화요일 아침.",
          b: [B("오늘 티비 보는 날이야?", 300, 130, "l", { w: 140 })],
        },
        {
          h: 440, bg: "kitchen",
          chars: [C("appa", 110, "sleepy", "hold", { o: "work" }), C("taeo", 300, "shock", "stand", { o: "pajama" })],
          n: "수요일 아침.",
          b: [B("아니, 어린이집 가는 날. 티비는 안 보는 날. 맛있는 건 저녁에.", 170, 96, "bl", { w: 250 }), B("아빠 어떻게 알았어?!", 310, 205, "b", { k: "shout", w: 140 })],
        },
        {
          h: 390, bg: "living",
          chars: [C("jaei", 110, "sly", "hip"), C("taeo", 300, "angry", "hip", { o: "pajama" })],
          n: "목요일 아침.",
          b: [B("오늘 티비 보는 날이야~? 맛있는 거 죠~!", 140, 100, "b", { w: 230 }), B("누나 따라 하지 마!", 310, 150, "b", { k: "shout", w: 140 })],
        },
        {
          h: 420, bg: "living",
          chars: [C("appa", 100, "proud", "give", { o: "work" }), C("taeo", 330, "blank", "stand", { o: "pajama" })],
          fp: [["notebook", 222, 252, { t: "오늘은?", s: 0.9, c: "#bfe3ff", lines: ["어린이집 가는 날 ✔", "티비 없는 날", "맛있는 건 저녁에"] }]],
          n: "금요일 아침.",
          b: [B("짠! 이제 이거 보면 돼!", 120, 95, "b", { w: 190 })],
        },
        {
          h: 280, bg: "burst:e6e0ff",
          chars: [bust("taeo", 200, 175, 1.4, "blank", "stand", { o: "pajama" })],
          b: [B("아빠… 나 글씨 못 읽어.", 200, 40, "", { w: 240 })],
          sfx: [FX("앗", 340, 230, { rot: 10, c: "#3b6fd6", size: 1.2 })],
        },
        {
          h: 340, bg: "bedroom-night",
          chars: [C("taeo", 140, "smile", "stand", { o: "pajama" }), C("eomma", 290, "smile", "stand", { o: "sick" })],
          n: "금요일 밤.",
          b: [B("엄마, 내일은… 어린이집 안 가는 날이지?", 150, 92, "b", { k: "whisper", w: 180 })],
        },
        {
          h: 320, bg: "sparkle:fff0d6",
          chars: [bust("eomma", 200, 190, 1.25, "teary", "stand", { o: "sick" })],
          b: [B("응. 내일은 하루 종일 엄마 아빠랑 있는 날.", 200, 44, "", { w: 280 })],
        },
        {
          h: 320, bg: "sparkle:ffe3ee",
          chars: [bust("taeo", 200, 190, 1.4, "happy", "stand", { o: "pajama" })],
          b: [B("그럼 맛있는 거 안 죠도 돼.", 200, 44, "", { w: 260 })],
        },
        {
          h: 360, bg: "sparkle:ffe3ee",
          chars: [C("taeo", 160, "happy", "hug", { o: "pajama" }), C("eomma", 250, "teary", "hug", { o: "sick" })],
          fp: [["heart", 330, 120, {}], ["heart", 70, 150, { s: 0.8 }]],
          b: [B("엄마 아빠랑 노는 게 제일 맛있어.", 200, 38, "", { w: 270 })],
          n2: "매일 아침 묻던 그 말은, 사실 ‘같이 있고 싶어’였다.",
        },
        {
          h: 430, bg: "living",
          chars: [C("appa", 55, "happy", "up"), C("taeo", 150, "laugh", "cheer"), C("jaei", 250, "happy", "cheer"), C("eomma", 345, "happy", "wave")],
          n: "토요일 아침.",
          b: [B("오늘 티비 보는 날이야?", 165, 176, "b", { w: 150 }), B("아니! 오늘은 놀이터 가는 날!", 130, 92, "bl", { k: "shout", w: 240 })],
        },
        {
          h: 280, bg: "burst:ffe27a",
          chars: [bust("taeo", 200, 180, 1.45, "laugh", "cheer")],
          b: [B("그리고 맛있는 거 죠!", 200, 40, "", { k: "shout", w: 260 })],
          sfx: [FX("하하하", 70, 230, { rot: -10, c: "#ff9f1c" }), FX("하하", 340, 240, { rot: 10, c: "#f0609d" })],
        },
      ],
    },
    // ───────────────────────── 8화 ─────────────────────────
    {
      id: 8,
      title: "피노키오 아빠",
      summary: "“아빠 내 말 안 들으면 피노키오야!” “엄마 맛있는 거 안 주면 소리 지른다!” 태오의 협박(?) 작전이 시작됐다.",
      lesson: "약속은 지키고, 부탁은 예쁘게. 어른도 아이도 똑같아요.",
      talk: "요즘 우리 가족이 “이따가” 하고 못 지킨 약속이 있나요? 떼쓰는 대신 “주세요”라고 말해 본 적은요?",
      cover: 2,
      panels: [
        {
          h: 380, bg: "living",
          chars: [C("taeo", 110, "happy", "give"), C("appa", 290, "sleepy", "hold")],
          fp: [["dino", 60, 356, { s: 0.9 }], ["phone", 290, 233, { s: 0.8 }]],
          n: "토요일 오후.",
          b: [B("아빠! 공룡 놀이 해 줘!", 110, 100, "b", { w: 150 }), B("응~ 이따가 해 줄게.", 300, 64, "b", { w: 140 })],
        },
        {
          h: 360, bg: "living",
          chars: [C("taeo", 110, "worried", "stand"), C("appa", 290, "sleepy", "hold")],
          fp: [["phone", 290, 213, { s: 0.8 }], ["clock", 200, 60, {}]],
          n: "30분 뒤.",
          b: [B("아빠, 이따가 됐어?", 105, 110, "b", { w: 130 }), B("조금만… 더 이따가~", 300, 60, "b", { w: 130, k: "whisper" })],
        },
        {
          h: 320, bg: "burst:ffd1e1",
          chars: [bust("taeo", 200, 190, 1.45, "angry", "hip")],
          b: [B("아빠! 내 말 안 들으면 피노키오야!!", 200, 44, "", { k: "shout", w: 300 })],
        },
        {
          h: 280, bg: "burst:c9dcff",
          chars: [bust("appa", 200, 170, 1.35, "shock", "stand")],
          b: [B("피… 피노키오?", 200, 40, "", { w: 200 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 110, "determined", "point"), C("appa", 300, "shock", "nose")],
          b: [B("약속 안 지키면 코가 길어지잖아! 아빠 코 벌써 길어졌어!", 140, 70, "b", { w: 230 })],
          sfx: [FX("쭈우욱", 330, 210, { rot: 10, c: "#e0443e" })],
        },
        {
          h: 340, bg: "living",
          chars: [C("jaei", 110, "laugh", "cover"), C("appa", 290, "guilty", "nose")],
          b: [B("진짜 길어진 것 같아!", 120, 60, "b", { w: 150 }), B("아… 아닌데?", 300, 60, "b")],
          sfx: [FX("깔깔깔", 150, 240, { rot: -8, c: "#ff9f1c" })],
        },
        {
          h: 400, bg: "kitchen",
          chars: [C("taeo", 110, "determined", "hip"), C("eomma", 295, "smile", "hip")],
          n: "그 작전, 부엌에서도 계속됐다.",
          b: [B("엄마! 맛있는 거 죠! 안 주면 소리 지른다!", 140, 110, "b", { k: "shout", w: 230 })],
        },
        {
          h: 300, bg: "sparkle:e6e0ff",
          chars: [bust("eomma", 200, 185, 1.3, "sly", "stand")],
          b: [B("그래? 소리 지르면 절대 못 주는데?", 200, 44, "", { w: 260 })],
        },
        {
          h: 300, bg: "burst:ffe27a",
          chars: [bust("taeo", 200, 190, 1.5, "angry", "cheer")],
          b: [B("맛있는 거 죠오오오!!", 200, 40, "", { k: "shout", w: 280 })],
          sfx: [FX("쩌렁쩌렁", 80, 250, { rot: -10, c: "#e0443e" }), FX("!!", 350, 230, { rot: 10, c: "#3b6fd6" })],
        },
        {
          h: 360, bg: "kitchen",
          chars: [C("taeo", 110, "sad", "stand"), C("eomma", 295, "blank", "stand")],
          b: [B("…방금 못 준다고 했지?", 295, 56, "b", { w: 150 }), B("힝…", 105, 130, "b", { k: "whisper" })],
        },
        {
          h: 360, bg: "kitchen",
          chars: [C("jaei", 120, "wink", "mouth"), C("taeo", 290, "surprised", "stand")],
          b: [B("태오야, 누나가 마법의 말 알려 줄까? ‘주세요’ 해 봐.", 150, 60, "b", { k: "whisper", w: 230 })],
        },
        {
          h: 300, bg: "sparkle:ffe3ee",
          chars: [bust("taeo", 200, 190, 1.45, "shy", "give")],
          b: [B("엄마… 맛있는 거 주세요.", 200, 44, "", { w: 240 })],
        },
        {
          h: 380, bg: "kitchen",
          chars: [C("taeo", 110, "love", "cheer"), C("eomma", 295, "happy", "give", { f: -1 })],
          fp: [["cake", 205, 250, { s: 0.8 }]],
          b: [B("이렇게 예쁘게 말하면 당연히 주지~!", 280, 60, "b", { w: 170 })],
          sfx: [FX("짠!", 205, 150, { rot: -8, c: "#ff6b6b" })],
        },
        {
          h: 300, bg: "sparkle:fff4c7",
          chars: [bust("taeo", 200, 190, 1.45, "eating", "mouth")],
          b: [B("(‘주세요’는… 진짜 마법이다!)", 200, 44, "", { k: "think", w: 250 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 110, "shy", "give"), C("appa", 290, "surprised", "hold")],
          fp: [["phone", 290, 233, { s: 0.8 }]],
          b: [B("아빠, 공룡 놀이 해 주세요.", 110, 100, "b", { w: 150 })],
        },
        {
          h: 320, bg: "sparkle:fff0d6",
          chars: [bust("appa", 200, 185, 1.3, "teary", "stand")],
          b: [B("…아빠가 먼저 약속을 안 지켰네. 미안해, 태오야. 지금 하자!", 200, 44, "", { w: 300 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("appa", 130, "laugh", "cheer"), C("taeo", 300, "laugh", "run")],
          fp: [["dino", 215, 356, { s: 1.2, f: -1 }]],
          b: [B("크아앙! 피노키오 공룡이 나타났다!", 140, 60, "b", { k: "shout", w: 220 })],
          sfx: [FX("꺄아아", 330, 120, { rot: 10, c: "#f0609d" })],
        },
        {
          h: 380, bg: "bedroom-night",
          chars: [C("appa", 110, "sly", "hip"), C("taeo", 290, "sleepy", "stand", { o: "pajama" })],
          n: "그날 밤.",
          b: [B("태오야, 이제 자야지. 안 자면…", 150, 70, "bl", { w: 220 }), B("피노키오야?", 300, 150, "b")],
        },
        {
          h: 330, bg: "bedroom-night",
          chars: [bust("appa", 110, 200, 1.1, "laugh", "stand"), bust("taeo", 300, 210, 1.2, "laugh", "stand", { o: "pajama" })],
          b: [B("아니! 아빠가 소리 지른다~!", 130, 50, "b", { k: "shout", w: 200 })],
          sfx: [FX("하하하", 300, 70, { rot: 8, c: "#ff9f1c" })],
        },
        {
          h: 150, bg: "sparkle:fff0d6",
          fp: [["heart", 340, 100, { s: 0.9 }]],
          n: "우리 집엔 이제 약속과 ‘주세요’가 있다.",
        },
      ],
    },
    // ───────────────────────── 9화 ─────────────────────────
    {
      id: 9,
      title: "김태오!",
      summary: "머리끈 뺏기, 흉내 내기, 그림에 낙서까지… 참고 또 참던 누나가 드디어 폭발했다. “김태오!” 그리고 엉덩이 찰싹!",
      lesson: "좋아하는 마음은 괴롭히지 말고 “좋아”라고 말해요. 그리고 누나 품은 언제나 열려 있어요.",
      talk: "형제자매나 친구에게 장난치고 싶을 때, 대신 어떻게 마음을 전할 수 있을까요?",
      cover: 7,
      panels: [
        {
          h: 360, bg: "living",
          chars: [C("jaei", 150, "smile", "hold"), C("taeo", 320, "sly", "stand", { s: 0.95 })],
          fp: [["drawing", 150, 290, { s: 0.7 }], ["battery", 70, 90, { lv: 4, s: 0.8 }]],
          n: "재이 누나는 참을성이 많다.",
          sfx: [FX("누나 참을성", 70, 128, { c: "#2fbf5b", size: 0.45 })],
          b: [B("(흐흐…)", 250, 150, "br", { k: "think" })],
        },
        {
          h: 360, bg: "living",
          chars: [C("jaei", 110, "surprised", "stand"), C("taeo", 300, "laugh", "run")],
          fp: [["scrunchie", 342, 150, {}], ["battery", 70, 60, { lv: 3, s: 0.7 }]],
          b: [B("누나 머리끈 내 거다~!", 300, 60, "b", { k: "shout", w: 170 }), B("(…참자. 누나니까.)", 120, 140, "b", { k: "think", w: 120 })],
          sfx: [FX("휙!", 220, 170, { rot: -10, c: "#3b6fd6" })],
        },
        {
          h: 340, bg: "living",
          chars: [C("jaei", 110, "blank", "stand"), C("taeo", 300, "sly", "hip")],
          fp: [["battery", 70, 60, { lv: 2, s: 0.7 }]],
          b: [B("참자~ 누나니까~ 메롱~", 300, 80, "b", { w: 150 })],
          sfx: [FX("부들부들", 205, 250, { rot: -6, c: "#e0443e", size: 0.7 })],
        },
        {
          h: 340, bg: "living",
          chars: [C("taeo", 110, "laugh", "hold")],
          fp: [["drawing", 280, 250, { s: 1.2, v: "scribble" }], ["battery", 330, 60, { lv: 1, s: 0.7 }]],
          b: [B("누나 그림 더 멋지게 해 줄게~", 120, 70, "b", { w: 170 })],
          sfx: [FX("쓱싹쓱싹", 280, 150, { rot: 8, c: "#6c8fd6" })],
        },
        {
          h: 280, bg: "burst:e8f7c8",
          chars: [bust("taeo", 120, 170, 1.2, "sly", "hip"), bust("jaei", 300, 180, 1.2, "shock", "nose")],
          fp: [["battery", 210, 50, { lv: 0, s: 0.9 }]],
          sfx: [FX("뿌웅~", 210, 240, { rot: -6, c: "#8a6d52", size: 1.2 })],
        },
        {
          h: 330, bg: "burst:ff9f9f",
          chars: [bust("jaei", 200, 200, 1.5, "angry", "hip")],
          b: [B("김태오!!!", 200, 50, "", { k: "shout", w: 240 })],
          sfx: [FX("펑!", 60, 150, { rot: -12, c: "#e0443e", size: 1.2 }), FX("펑!", 345, 170, { rot: 12, c: "#e0443e", size: 1.2 })],
        },
        {
          h: 260, bg: "speed:fff3f6",
          chars: [C("taeo", 110, "shock", "run", { s: 0.85, f: -1 }), C("jaei", 300, "angry", "run", { s: 0.85, f: -1 })],
          sfx: [FX("다다다다", 200, 60, { rot: -4, c: "#3b6fd6" })],
          b: [B("으아아 도망!", 110, 60, "b")],
        },
        {
          h: 300, bg: "burst:ffe27a",
          chars: [bust("taeo", 200, 200, 1.5, "cry", "stand")],
          sfx: [FX("찰싹!", 200, 60, { rot: -8, c: "#e0443e", size: 1.8 })],
          b: [B("으앙~ 내 엉덩이!", 320, 180, "l", { w: 110 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 80, "cry", "stand"), C("eomma", 200, "angry", "hip"), C("jaei", 320, "guilty", "stand")],
          b: [B("무슨 일이야!", 200, 44, "b", { k: "shout" })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 110, "cry", "eyes"), C("eomma", 290, "angry", "point", { f: -1 })],
          b: [B("태오! 누나 머리끈 뺏고, 그림에 낙서하고! 누나 괴롭히면 돼, 안 돼?", 270, 60, "b", { w: 230 }), B("안… 돼…", 110, 150, "b", { k: "whisper" })],
        },
        {
          h: 280, bg: "gloom",
          chars: [bust("taeo", 200, 180, 1.4, "cry", "stand")],
          n: "엄마한테 혼난 태오는 구석에서 훌쩍였다.",
        },
        {
          h: 360, bg: "living",
          chars: [bust("jaei", 200, 190, 1.35, "teary", "stand")],
          n: "그런데 이상하다.",
          n2: "동생이 혼나는 걸 보면, 누나 마음이 더 아프다.",
        },
        {
          h: 360, bg: "sparkle:ffe3ee",
          chars: [C("taeo", 245, "cry", "hug"), C("jaei", 150, "teary", "hug")],
          fp: [["heart", 330, 100, {}]],
          b: [B("태오야, 누나도 엉덩이 때려서 미안해.", 200, 40, "", { w: 260 })],
        },
        {
          h: 330, bg: "sparkle:ffe3ee",
          chars: [bust("taeo", 200, 200, 1.4, "teary", "stand")],
          b: [B("나도 미안해… 누나가 좋아서 그랬어.", 200, 44, "", { w: 260 })],
        },
        {
          h: 300, bg: "sparkle:fff4c7",
          chars: [bust("jaei", 150, 190, 1.3, "shy", "cheeks")],
          fp: [["battery", 320, 150, { lv: 4, s: 1.1 }]],
          b: [B("(…좋아서 괴롭힌 거였어?)", 150, 44, "", { k: "think", w: 220 })],
          sfx: [FX("참을성 100% 충전!", 300, 230, { rot: -6, c: "#2fbf5b", size: 0.5 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 300, "sly", "run"), C("jaei", 110, "sly", "hip")],
          fp: [["scrunchie", 342, 170, {}]],
          n: "다음 날.",
          b: [B("누나~ 머리끈!", 300, 90, "b", { k: "shout" }), B("…김태오?", 110, 130, "b")],
          sfx: [FX("도망!", 300, 360, { rot: 8, c: "#3b6fd6", size: 0.8 })],
        },
        {
          h: 160, bg: "sparkle:fff0d6",
          fp: [["heart", 60, 110, { s: 0.8 }], ["heart", 345, 90, {}]],
          n: "우리 집 누나와 동생은",
          n2: "오늘도 이렇게 사이가 좋다.",
        },
      ],
    },
    // ───────────────────────── 10화 ─────────────────────────
    {
      id: 10,
      title: "태오는 다 듣고 있다",
      summary: "혼자 노는 줄만 알았던 태오. 그런데 어른들이 소곤소곤 한 말까지 다 듣고 있었다. “왜 놀려! 놀리지 마!”",
      lesson: "아이는 혼자 노는 것 같아도 다 듣고 있어요. 그러니 아이 곁에서는 따뜻한 말을.",
      talk: "오늘 가족에게 들은 말 중에 제일 기분 좋았던 말은 뭐예요?",
      cover: 11,
      panels: [
        {
          h: 360, bg: "living",
          chars: [C("taeo", 130, "determined", "kick")],
          fp: [["figures", 300, 336, { s: 1.1 }]],
          n: "태오는 혼자서도 잘 논다.",
          sfx: [FX("슈웅~ 쾅!", 290, 150, { rot: 8, c: "#3b6fd6" })],
        },
        {
          h: 380, bg: "kitchen",
          chars: [C("appa", 100, "smile", "stand"), C("eomma", 290, "smile", "hold")],
          b: [B("태오 요즘 혼자서도 잘 노네.", 110, 70, "b", { w: 160 }), B("응. 우리 말은 하나도 안 듣는 것 같아.", 290, 60, "b", { w: 160 })],
        },
        {
          h: 280, bg: "sparkle:e6e0ff",
          chars: [bust("taeo", 200, 180, 1.45, "sly", "stand")],
          b: [B("(다 듣고 있지롱.)", 200, 44, "", { k: "think", w: 220 })],
        },
        {
          h: 400, bg: "living",
          chars: [C("taeo", 110, "happy", "give"), C("appa", 295, "surprised", "hold")],
          fp: [["tablet", 295, 262, { s: 0.9 }]],
          b: [B("아빠! 패드로 어벤져스 게임 하자!", 120, 90, "b", { w: 170 }), B("패드? 이 태블릿?", 300, 60, "b", { w: 130 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 150, "angry", "cheer")],
          fp: [["boardgame", 150, 120, { s: 1.5 }]],
          b: [B("아니! 이거!", 320, 90, "l", { k: "shout" })],
          sfx: [FX("짠!", 300, 250, { rot: 8, c: "#ff6b6b", size: 1.2 })],
        },
        {
          h: 280, bg: "burst:dff3e4",
          chars: [bust("appa", 200, 170, 1.3, "blank", "stand")],
          b: [B("…이게 패드야?", 200, 40, "", { w: 200 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 110, "love", "point"), C("jaei", 300, "smile", "hold")],
          fp: [["boardgame", 200, 356, { s: 0.9 }]],
          b: [B("나는 블랙 위도우랑 수! 제일 예뻐!", 120, 70, "b", { w: 170 }), B("그럼 누나는 쉬터맨…아니, 스파이더맨!", 300, 90, "b", { w: 150 })],
        },
        {
          h: 360, bg: "living",
          chars: [C("taeo", 110, "worried", "scratch"), C("appa", 300, "smile", "stand")],
          b: [B("아빠, 늘어나는 애 이름 뭐야?", 110, 70, "b", { w: 150 }), B("리드.", 300, 60, "b")],
        },
        {
          h: 260, bg: "speed:eef4ff",
          chars: [bust("taeo", 120, 170, 1.1, "worried", "scratch")],
          n: "3분 뒤.",
          b: [B("아빠, 늘어나는 애 이름 뭐야?", 290, 110, "l", { w: 150 })],
          sfx: [FX("또?!", 330, 220, { rot: 10, c: "#3b6fd6" })],
        },
        {
          h: 400, bg: "living",
          chars: [C("appa", 60, "smile", "stand"), C("taeo", 170, "worried", "stand"), C("jaei", 280, "smile", "hold"), C("eomma", 360, "smile", "stand", { s: 0.9 })],
          fp: [["boardgame", 200, 380, { s: 0.9 }]],
          b: [B("카드에 적힌 숫자만큼 가는 거야. 태오 이거 읽을 수 있어?", 250, 60, "b", { w: 220 })],
        },
        {
          h: 360, bg: "living",
          chars: [C("appa", 150, "sly", "mouth"), C("eomma", 300, "smile", "stand")],
          b: [B("(태오는 아직 글씨랑 숫자 잘 모르잖아~)", 170, 70, "b", { k: "whisper", w: 200 })],
        },
        {
          h: 330, bg: "burst:ffd1e1",
          chars: [bust("taeo", 190, 200, 1.45, "angry", "point")],
          b: [B("왜 놀려! 놀리지 마!!", 200, 44, "", { k: "shout", w: 260 })],
          sfx: [FX("삿대질!", 330, 280, { rot: 10, c: "#e0443e", size: 0.7 })],
        },
        {
          h: 360, bg: "living",
          chars: [C("appa", 110, "shock", "stand"), C("jaei", 300, "laugh", "cover")],
          b: [B("어떻게 들었지? 속삭였는데…", 110, 60, "b", { w: 150 }), B("아빠, 태오는 다 들어!", 300, 80, "b", { w: 140 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("eomma", 110, "happy", "give"), C("taeo", 300, "laugh", "cheer")],
          b: [B("그럼 우리 태오가 제일 잘하는 놀이 하자!", 120, 60, "b", { w: 170 }), B("오구마꼬치 피었습니다!", 300, 110, "b", { k: "shout", w: 150 })],
        },
        {
          h: 280, bg: "burst:e6e0ff",
          chars: [bust("jaei", 200, 180, 1.35, "blank", "stand")],
          b: [B("…오구마꼬치? 무궁화 꽃이 피었습니다겠지.", 200, 44, "", { w: 280 })],
        },
        {
          h: 300, bg: "burst:ffe27a",
          chars: [bust("taeo", 200, 190, 1.5, "angry", "hip")],
          b: [B("아니야! 오구마꼬치 맞아!! 어린이집에서도 그렇게 해!!", 200, 44, "", { k: "shout", w: 300 })],
          sfx: [FX("빡빡", 60, 250, { rot: -10, c: "#e0443e", size: 0.8 })],
        },
        {
          h: 360, bg: "living",
          chars: [C("jaei", 110, "sly", "hold"), C("taeo", 300, "worried", "stand")],
          fp: [["notebook", 170, 232, { t: "놀이 책", s: 0.8, c: "#b8e0ff", lines: ["무궁화 꽃이", "피었습니다"] }]],
          b: [B("여기 책에도 ‘무궁화 꽃이’라고 쓰여 있는데?", 150, 60, "b", { w: 200 })],
        },
        {
          h: 320, bg: "sparkle:fff4c7",
          chars: [bust("taeo", 200, 200, 1.45, "shy", "scratch")],
          b: [B("…헤헤. 무궁…꼬치?", 200, 44, "", { w: 220 })],
          sfx: [FX("긁적긁적", 320, 270, { rot: 8, c: "#8a6d52", size: 0.8 })],
        },
        {
          h: 400, bg: "living",
          chars: [C("taeo", 60, "happy", "eyes"), C("appa", 170, "determined", "kick"), C("eomma", 265, "surprised", "up"), C("jaei", 350, "laugh", "cheer")],
          b: [B("오구마꼬치~ 피었습니다!", 90, 80, "b", { k: "shout", w: 170 })],
          sfx: [FX("얼음!", 300, 110, { rot: 8, c: "#3b6fd6" })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 110, "laugh", "point"), C("appa", 300, "guilty", "kick")],
          b: [B("아빠 움직였다! 아빠 아웃!", 120, 80, "b", { k: "shout", w: 160 })],
          sfx: [FX("하하하", 210, 300, { rot: 8, c: "#ff9f1c" })],
        },
        {
          h: 440, bg: "living-night",
          chars: [C("eomma", 110, "worried", "stand"), C("appa", 290, "guilty", "scratch")],
          n: "그날 밤, 거실.",
          b: [B("(태오가 글씨 모른다는 말에 속상했나 봐.)", 120, 90, "b", { k: "whisper", w: 170 }), B("(그러게. 아빠가 너무 쉽게 말했네.)", 300, 120, "b", { k: "whisper", w: 150 })],
        },
        {
          h: 330, bg: "bedroom-night",
          bp: [["bed", 200, 306, { w: 330 }], ["pillow", 90, 250, {}]],
          chars: [C("taeo", 195, "sly", "stand", { o: "pajama", rot: -90, y: 262, s: 0.95 })],
          fp: [["blanket", 215, 296, { w: 190, h: 56, c: "#bfe3ff" }]],
          b: [B("(…다 들린다.)", 280, 90, "bl", { k: "think" })],
        },
        {
          h: 380, bg: "living-night",
          chars: [bust("eomma", 100, 260, 1.1, "teary", "stand"), bust("appa", 300, 270, 1.1, "happy", "stand")],
          b: [B("그래도 우리 태오는 글씨는 몰라도, 가족 마음 읽는 건 1등이야.", 130, 60, "b", { k: "whisper", w: 230 }), B("오구마꼬치도 세계 1등이고.", 310, 150, "b", { k: "whisper", w: 140 })],
        },
        {
          h: 330, bg: "bedroom-night",
          bp: [["bed", 200, 306, { w: 330 }], ["pillow", 90, 250, {}]],
          chars: [C("taeo", 195, "shy", "stand", { o: "pajama", rot: -90, y: 262, s: 0.95 })],
          fp: [["blanket", 215, 296, { w: 190, h: 56, c: "#bfe3ff" }], ["heart", 300, 100, {}], ["heart", 340, 140, { s: 0.7 }]],
          n: "태오는 오늘도 다 듣고 있다.",
        },
        {
          h: 150, bg: "sparkle:fff0d6",
          fp: [["heart", 60, 110, { s: 0.8 }], ["heart", 345, 50, {}]],
          n2: "그래서 우리는, 좋은 말만 들려주기로 했다.",
        },
      ],
    },
    // ───────────────────────── 11화 ─────────────────────────
    {
      id: 11,
      title: "다리가 부러진 영웅",
      summary: "장난감 영웅이 잔뜩인 태오. 그런데 다리가 부러진 초록 영웅은 늘 상자 구석에만 있다. 그러던 어느 날, 태오 다리가 삐끗했다.",
      lesson: "다리가 아파도, 모양이 달라져도 소중한 친구예요. 아플 때 곁에 있어 주는 게 진짜 영웅이에요.",
      talk: "우리 집에 오래 안 가지고 논 장난감이 있나요? 그 장난감에게 한마디 해 줄까요?",
      cover: 12,
      panels: [
        {
          h: 400, bg: "living",
          chars: [C("taeo", 110, "laugh", "cheer")],
          fp: [["figures", 280, 376, { s: 1.2 }], ["toybox", 330, 290, { s: 0.7 }]],
          n: "태오에게는 장난감 영웅이 잔뜩 있다.",
          b: [B("블루베리 출동! 쉬터맨도 출동!", 170, 110, "bl", { k: "shout", w: 240 })],
        },
        {
          h: 280, bg: "gloom",
          fp: [["toybox", 200, 250, { s: 1.6 }], ["brokentoy", 200, 200, { s: 1.4, fallen: true }]],
          n: "그런데 상자 구석, 다리가 부러진 초록 영웅은…",
          n2: "오늘도 출동하지 못했다.",
        },
        {
          h: 360, bg: "living",
          chars: [C("jaei", 110, "smile", "point"), C("taeo", 300, "blank", "stand")],
          b: [B("태오야, 초록 영웅은 왜 안 데리고 놀아?", 120, 70, "b", { w: 170 }), B("걔는 다리 부러졌잖아. 못 뛰어.", 300, 90, "b", { w: 150 })],
        },
        {
          h: 400, bg: "living",
          chars: [C("taeo", 200, "surprised", "kick", { rot: -12 })],
          n: "그다음 날, 태권도 발차기 연습을 하다가…",
          sfx: [FX("얍!", 90, 110, { rot: -10, c: "#3b6fd6" }), FX("삐끗!", 300, 320, { rot: 10, c: "#e0443e", size: 1.2 })],
        },
        {
          h: 300, bg: "burst:c9dcff",
          chars: [bust("taeo", 200, 190, 1.45, "cry", "stand")],
          b: [B("으아앙~ 다리 아파!", 200, 44, "", { k: "shout", w: 240 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("taeo", 100, "sad", "stand"), C("eomma", 290, "worried", "stand")],
          fp: [["bandage", 106, 356, { s: 0.9 }]],
          b: [B("살짝 삐었네. 며칠은 뛰면 안 돼.", 290, 60, "b", { w: 160 }), B("그럼 나 이제 못 놀아?", 110, 110, "b", { w: 130 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("appa", 150, "happy", "hold"), C("taeo", 150, "surprised", "up", { y: 214, s: 0.9 })],
          fp: [["bandage", 172, 200, { s: 0.7 }]],
          b: [B("무슨 소리! 오늘은 아빠가 태오 다리다!", 290, 90, "l", { w: 150 })],
          sfx: [FX("번쩍!", 300, 250, { rot: 8, c: "#ff9f1c" })],
        },
        {
          h: 360, bg: "living",
          chars: [C("jaei", 110, "happy", "give"), C("taeo", 290, "smile", "stand")],
          fp: [["boardgame", 200, 336, { s: 0.9 }], ["bandage", 296, 336, { s: 0.9 }]],
          b: [B("누나는 앉아서 하는 패드 게임 해 줄게!", 120, 70, "b", { w: 170 })],
        },
        {
          h: 420, bg: "halmae",
          chars: [C("halmeoni", 110, "smile", "give", { o: "apron" }), C("harabeoji", 300, "happy", "stand")],
          n: "할머니 할아버지도 달려오셨다.",
          b: [B("아이고 우리 강아지, 할머니가 맛있는 거 해 왔다.", 150, 96, "b", { w: 230 })],
        },
        {
          h: 300, bg: "sparkle:fff4c7",
          chars: [bust("taeo", 200, 190, 1.45, "love", "stand")],
          b: [B("다리 아파도… 다들 나랑 놀아 주네.", 200, 44, "", { w: 260 })],
        },
        {
          h: 300, bg: "living-night",
          chars: [bust("taeo", 110, 200, 1.1, "surprised", "stand", { o: "pajama" })],
          fp: [["toybox", 300, 260, { s: 1.2 }], ["brokentoy", 300, 220, { s: 1.1, fallen: true }]],
          n: "그날 밤, 장난감 상자를 보다가.",
          b: [B("(…너도 심심했지?)", 150, 70, "br", { k: "think" })],
        },
        {
          h: 340, bg: "living-night",
          chars: [C("taeo", 130, "determined", "hold", { o: "pajama" })],
          fp: [["brokentoy", 180, 300, { s: 1.1, band: true }]],
          b: [B("내가 반창고 붙여 줄게. 이제 너도 출동이야!", 280, 90, "l", { w: 150 })],
          sfx: [FX("찰칵", 250, 250, { rot: 8, c: "#8a6d52", size: 0.7 })],
        },
        {
          h: 380, bg: "sparkle:ffe3ee",
          chars: [C("taeo", 110, "laugh", "cheer", { o: "pajama" })],
          fp: [["brokentoy", 260, 330, { s: 1.4, band: true }], ["figures", 330, 356, { s: 0.8 }], ["heart", 260, 130, {}]],
          b: [B("다리 아파도 영웅이야! 제일 용감한 초록 영웅!", 140, 70, "b", { k: "shout", w: 220 })],
        },
        {
          h: 400, bg: "bedroom-night",
          chars: [C("jaei", 110, "teary", "stand", { o: "pajama" }), C("eomma", 290, "teary", "stand", { o: "sick" })],
          b: [B("(태오가… 초록 영웅이랑 자네.)", 110, 70, "b", { k: "whisper", w: 150 }), B("(아파 보니까 알았나 봐.)", 290, 70, "b", { k: "whisper", w: 140 })],
        },
        {
          h: 330, bg: "bedroom-night",
          bp: [["bed", 200, 306, { w: 330 }], ["pillow", 90, 250, {}]],
          chars: [C("taeo", 195, "sleepy", "stand", { o: "pajama", rot: -90, y: 262, s: 0.95 })],
          fp: [["blanket", 215, 296, { w: 190, h: 56, c: "#bfe3ff" }], ["brokentoy", 160, 250, { s: 0.9, band: true }]],
          n: "아플 때 곁에 있어 주는 게 진짜 영웅이다.",
        },
      ],
    },
    // ───────────────────────── 12화 ─────────────────────────
    {
      id: 12,
      title: "어벤져스에 가년~",
      summary: "“어벤져스에 가년~ 블루베리도 있고!” 태오가 만든 놀이에 온 가족이 모였다. 그런데 태오어를 모르면 바로 땡!",
      lesson: "우리 가족이 바로, 서로를 지켜 주는 어벤져스예요.",
      talk: "‘우리 집에 가면~’ 놀이를 해 볼까요? 우리 가족에게 있는 것을 하나씩 이어 말해 봐요.",
      cover: 6,
      panels: [
        {
          h: 360, bg: "living-night",
          chars: [C("jaei", 36, "smile", "stand", { s: 0.82 }), C("halmeoni", 98, "smile", "stand", { s: 0.72 }), C("eomma", 163, "smile", "stand", { s: 0.72 }), C("appa", 232, "smile", "stand", { s: 0.72 }), C("harabeoji", 300, "smile", "stand", { s: 0.72 }), C("taeo", 362, "laugh", "cheer", { s: 0.82 })],
          n: "저녁을 먹고, 온 가족이 거실에 모였다.",
          b: [B("어벤져스에 가년 놀이 하자!", 290, 90, "br", { k: "shout", w: 200 })],
        },
        {
          h: 280, bg: "burst:e6e0ff",
          chars: [bust("jaei", 200, 180, 1.35, "blank", "stand")],
          b: [B("…가년? ‘시장에 가면’ 놀이 말하는 거지? ‘가면’이야.", 200, 44, "", { w: 280 })],
        },
        {
          h: 300, bg: "burst:ffe27a",
          chars: [bust("taeo", 200, 190, 1.5, "angry", "hip")],
          b: [B("가년 맞아!! 어벤져스는 가년이야!!", 200, 44, "", { k: "shout", w: 280 })],
        },
        {
          h: 360, bg: "living-night",
          chars: [C("jaei", 110, "smile", "shrug"), C("taeo", 300, "laugh", "cheer")],
          b: [B("그래, 가년 하자~", 110, 80, "b"), B("어벤져스에 가년~ 블루베리도 있고!", 300, 110, "b", { w: 160 })],
        },
        {
          h: 360, bg: "living-night",
          chars: [C("jaei", 110, "happy", "point"), C("taeo", 300, "love", "stand")],
          b: [B("어벤져스에 가년~ 블루베리도 있고, 쉬터맨도 있고!", 130, 70, "b", { w: 200 })],
        },
        {
          h: 380, bg: "living-night",
          chars: [C("appa", 110, "proud", "hip"), C("taeo", 300, "shock", "stand")],
          b: [B("어벤져스에 가년~ 블루베리도 있고, 쉬터맨도 있고, 스티브 로저스도 있고!", 140, 70, "b", { w: 230 })],
        },
        {
          h: 320, bg: "burst:ffd1e1",
          chars: [bust("taeo", 190, 200, 1.45, "angry", "point")],
          b: [B("땡!! 스테잌로저야!!", 200, 44, "", { k: "shout", w: 260 })],
        },
        {
          h: 360, bg: "living-night",
          chars: [C("appa", 110, "shy", "scratch"), C("jaei", 300, "laugh", "cover")],
          b: [B("아… 스테잌로저…", 110, 70, "b")],
          sfx: [FX("긁적긁적", 150, 260, { rot: 8, c: "#8a6d52", size: 0.8 }), FX("깔깔깔", 300, 90, { rot: -8, c: "#ff9f1c" })],
        },
        {
          h: 380, bg: "living-night",
          chars: [C("eomma", 110, "happy", "point"), C("taeo", 300, "laugh", "cheer")],
          b: [B("…스테잌로저도 있고, 늘어나는 애도 있고!", 130, 70, "b", { w: 200 }), B("엄마 잘한다!", 300, 150, "b")],
        },
        {
          h: 280, bg: "sparkle:e6e0ff",
          chars: [bust("taeo", 120, 180, 1.15, "worried", "scratch"), bust("eomma", 300, 180, 1.1, "blank", "stand")],
          b: [B("근데 엄마, 늘어나는 애 이름 뭐야?", 130, 44, "b", { w: 200 }), B("…너도 몰라?", 310, 60, "b")],
        },
        {
          h: 400, bg: "living-night",
          chars: [C("harabeoji", 110, "worried", "think"), C("taeo", 300, "surprised", "stand")],
          b: [B("허허, 할아버지 차례구나. 어벤져스에 가면… 우… 우엉?", 130, 80, "b", { w: 200 })],
        },
        {
          h: 300, bg: "burst:c8f5c8",
          chars: [bust("taeo", 120, 190, 1.2, "laugh", "cheer"), bust("harabeoji", 300, 190, 1.15, "proud", "stand")],
          b: [B("맞아!! 우엉 있어! 할아버지 통과!", 130, 44, "b", { k: "shout", w: 200 })],
          sfx: [FX("얼떨결에 정답", 300, 90, { rot: 8, c: "#2fbf5b", size: 0.5 })],
        },
        {
          h: 400, bg: "living-night",
          chars: [C("halmeoni", 110, "worried", "think"), C("taeo", 300, "smile", "stand")],
          b: [B("어벤져스에 가면… 블루…베리도 있고… 에고, 할머니는 모르겠다.", 140, 80, "b", { w: 220 })],
        },
        {
          h: 330, bg: "sparkle:fff0d6",
          chars: [bust("halmeoni", 200, 200, 1.3, "happy", "stand")],
          b: [B("어벤져스에 가면… 우리 태오도 있고!", 200, 44, "", { w: 260 })],
        },
        {
          h: 300, bg: "sparkle:ffe3ee",
          chars: [bust("taeo", 200, 190, 1.45, "love", "cheeks")],
          b: [B("나도 어벤져스야?", 200, 44, "", { w: 220 })],
        },
        {
          h: 360, bg: "living-night",
          chars: [C("jaei", 110, "sly", "point"), C("taeo", 300, "shy", "scratch")],
          b: [B("그럼! 누나 괴롭히는 힘은 우주 최강이지.", 130, 70, "b", { w: 190 })],
          sfx: [FX("헤헤", 300, 110, { rot: 8, c: "#8a6d52", size: 0.8 })],
        },
        {
          h: 400, bg: "living-night",
          chars: [C("jaei", 36, "happy", "stand", { s: 0.82 }), C("halmeoni", 98, "happy", "stand", { s: 0.72 }), C("eomma", 163, "happy", "stand", { s: 0.72 }), C("appa", 232, "happy", "stand", { s: 0.72 }), C("harabeoji", 300, "happy", "stand", { s: 0.72 }), C("taeo", 362, "determined", "cheer", { s: 0.82 })],
          b: [B("어벤져스에 가년~ 할머니도 있고, 할아버지도 있고, 엄마도, 아빠도, 누나도 있고!", 200, 60, "", { k: "shout", w: 330 })],
        },
        {
          h: 420, bg: "sparkle:ffe3ee",
          chars: [C("jaei", 36, "laugh", "cheer", { s: 0.82 }), C("halmeoni", 98, "laugh", "cheer", { s: 0.72 }), C("eomma", 163, "laugh", "cheer", { s: 0.72 }), C("appa", 232, "laugh", "cheer", { s: 0.72 }), C("harabeoji", 300, "laugh", "cheer", { s: 0.72 }), C("taeo", 362, "laugh", "cheer", { s: 0.82 })],
          fp: [["heart", 200, 50, { s: 1.3 }]],
          b: [B("…그리고 나도 있고!", 290, 130, "br", { k: "shout", w: 180 })],
        },
        {
          h: 150, bg: "sparkle:fff0d6",
          fp: [["heart", 60, 110, { s: 0.8 }], ["heart", 345, 50, {}]],
          n2: "우리 집 어벤져스는 오늘도 여섯 명이다.",
        },
      ],
    },
    // ───────────────────────── 13화 ─────────────────────────
    {
      id: 13,
      title: "아빠 레몬 먹어!",
      summary: "“싫어하는 것도 먹어야 튼튼해지고 근육도 생겨.” 아빠가 태오에게 한 말이, 레몬이 되어 아빠에게 돌아왔다.",
      lesson: "내가 한 말은 아이가 그대로 돌려줘요. 먼저 해 보이는 게 최고의 잔소리예요.",
      talk: "우리 가족이 제일 싫어하는 음식은 뭐예요? 오늘 한 입씩 같이 도전해 볼까요?",
      cover: 4,
      panels: [
        {
          h: 360, bg: "kitchen",
          chars: [C("taeo", 130, "angry", "hip", { y: 300 })],
          fp: [["table", 200, 262, { w: 400 }], ["broccoli", 150, 262, { s: 1.1 }]],
          n: "저녁 식탁. 태오 접시엔 초록 나무가 세 그루.",
          b: [B("브로콜리 싫어!", 280, 90, "bl", { k: "shout" })],
        },
        {
          h: 380, bg: "kitchen",
          chars: [C("appa", 120, "proud", "fist", { y: 380 }), C("taeo", 300, "sad", "stand", { y: 320 })],
          fp: [["table", 200, 290, { w: 400 }], ["broccoli", 300, 290, {}]],
          b: [B("태오야, 싫어하는 것도 먹어야 튼튼해지고 근육도 생겨.", 150, 60, "b", { w: 230 })],
          sfx: [FX("불끈", 60, 200, { rot: -10, c: "#e0443e", size: 0.8 })],
        },
        {
          h: 280, bg: "burst:e8f7c8",
          chars: [bust("taeo", 200, 180, 1.45, "sick", "mouth")],
          sfx: [FX("우웩…", 320, 90, { rot: 8, c: "#3f9a4a" }), FX("꿀꺽", 80, 240, { rot: -8, c: "#8a6d52", size: 0.8 })],
        },
        {
          h: 340, bg: "kitchen",
          chars: [C("taeo", 150, "sly", "hold")],
          fp: [["lemon", 150, 290, { s: 1.1 }]],
          n: "다음 날, 과일 바구니에서 태오가 발견한 것.",
          b: [B("(흐흐흐…)", 290, 110, "l", { k: "think" })],
          sfx: [FX("반짝", 250, 230, { rot: 8, c: "#e3b100", size: 0.8 })],
        },
        {
          h: 320, bg: "burst:ffe27a",
          chars: [bust("taeo", 180, 200, 1.4, "determined", "give")],
          fp: [["lemon", 330, 270, { s: 1.4 }]],
          b: [B("아빠 레몬 먹어!!", 200, 44, "", { k: "shout", w: 240 })],
        },
        {
          h: 280, bg: "burst:c9dcff",
          chars: [bust("appa", 200, 170, 1.35, "shock", "stand")],
          b: [B("싫어! 그건 너무 시잖아!", 200, 40, "", { k: "shout", w: 240 })],
        },
        {
          h: 400, bg: "living",
          chars: [C("taeo", 110, "proud", "point"), C("appa", 300, "guilty", "stand")],
          fp: [["lemon", 200, 250, { s: 0.9 }]],
          b: [B("싫어하는 것도 먹어야 튼튼해지고 근육도 생겨!", 140, 70, "b", { k: "shout", w: 220 })],
          sfx: [FX("똑같이!", 300, 110, { rot: 8, c: "#3b6fd6", size: 0.8 })],
        },
        {
          h: 360, bg: "living",
          chars: [C("jaei", 110, "laugh", "cover"), C("eomma", 290, "laugh", "hip")],
          b: [B("아빠가 어제 한 말이랑 똑같아!", 110, 70, "b", { w: 150 }), B("태오는 다 듣고 있다니까~", 300, 70, "b", { w: 150 })],
          sfx: [FX("깔깔깔", 200, 260, { rot: -8, c: "#ff9f1c" })],
        },
        {
          h: 300, bg: "sparkle:e6e0ff",
          chars: [bust("appa", 200, 190, 1.35, "determined", "hold")],
          fp: [["lemon", 200, 290, { s: 1.2, cut: true }]],
          b: [B("…그래. 아빠가 한 말이니까 아빠가 먼저 먹어야지.", 200, 44, "", { w: 290 })],
        },
        {
          h: 300, bg: "burst:fff08a",
          chars: [bust("appa", 200, 190, 1.5, "shock", "mouth")],
          sfx: [FX("시큼!!!", 200, 50, { rot: -6, c: "#e3b100", size: 1.6 }), FX("부르르", 70, 250, { rot: -10, c: "#3b6fd6", size: 0.8 }), FX("부르르", 340, 250, { rot: 10, c: "#3b6fd6", size: 0.8 })],
        },
        {
          h: 380, bg: "living",
          chars: [C("appa", 130, "proud", "up"), C("taeo", 300, "love", "cheer")],
          b: [B("크으… 아빠 근육 생겼다!", 140, 70, "b", { k: "shout", w: 170 }), B("진짜?!", 310, 120, "b", { k: "shout" })],
          sfx: [FX("불끈불끈", 130, 330, { rot: -6, c: "#e0443e", size: 0.7 })],
        },
        {
          h: 380, bg: "kitchen",
          chars: [C("taeo", 130, "determined", "fist", { y: 320 }), C("appa", 300, "happy", "hip", { y: 380 })],
          fp: [["table", 200, 290, { w: 400 }], ["broccoli", 140, 290, { one: true }]],
          n: "그날 저녁.",
          b: [B("그럼 나도! 브로콜리 먹을래!", 140, 90, "b", { k: "shout", w: 170 })],
        },
        {
          h: 300, bg: "sparkle:fff4c7",
          chars: [bust("taeo", 200, 190, 1.45, "eating", "fist")],
          b: [B("나 근육 생겼어?", 200, 44, "", { w: 220 })],
          sfx: [FX("우물우물", 330, 260, { rot: 8, c: "#8a6d52", size: 0.8 })],
        },
        {
          h: 360, bg: "kitchen",
          chars: [C("taeo", 110, "sly", "give"), C("jaei", 300, "shock", "stand")],
          fp: [["lemon", 168, 286, { s: 0.9 }]],
          b: [B("이제 누나 차례! 누나 레몬 먹어!", 130, 70, "b", { k: "shout", w: 180 })],
        },
        {
          h: 300, bg: "burst:ff9f9f",
          chars: [bust("jaei", 200, 200, 1.45, "angry", "hip")],
          b: [B("김태오!!", 200, 50, "", { k: "shout", w: 220 })],
          sfx: [FX("도망!", 330, 250, { rot: 10, c: "#3b6fd6" })],
        },
        {
          h: 160, bg: "sparkle:fff0d6",
          fp: [["lemon", 60, 110, { s: 0.8, cut: true }], ["heart", 345, 60, {}]],
          n: "아빠가 한 말은 태오가 다 기억한다.",
          n2: "그래서 아빠는 오늘도 먼저 한 입 먹는다.",
        },
      ],
    },
  ];

  root.WebtoonData = { CHARACTERS, EPISODES };
})(typeof window !== "undefined" ? window : globalThis);
